/**
 * Hero 遮幅 class 转发（真源 `@/lib/traveltrustCinematicVisual` · TT-PH1-150）
 */
export {
  TT_CINEMATIC_FILM_DEPTH as TT_HERO_FILM_DEPTH,
  TT_CINEMATIC_FILM_INK as TT_HERO_FILM_INK,
  TT_HERO_LETTERBOX_BOTTOM_CLASS,
  TT_HERO_LETTERBOX_BOTTOM_UNIFIED_CLASS,
  TT_HERO_LETTERBOX_TOP_CLASS,
  TT_HERO_LETTERBOX_TOP_UNIFIED_CLASS,
  TT_HERO_LETTERBOX_WARM_BOTTOM_UNIFIED_CLASS,
  TT_HERO_LETTERBOX_WARM_TOP_UNIFIED_CLASS,
  TT_PAGE_CINEMATIC_LETTERBOX_OVERLAY,
} from "@/lib/traveltrustCinematicVisual";
