import {
  TT_MARKETING_BTN_MARKET_PRIMARY,
  TT_MARKETING_BTN_MARKET_PRIMARY_PILL,
  TT_MARKETING_GUIDES_ATMOSPHERE,
  TT_MARKETING_MARKET_DARK_PATH,
  TT_MARKETING_MARKET_L5_LIST_CARD_FRAME,
  TT_MARKETING_MARKET_L5_LIST_CARD_INNER,
  TT_MARKETING_MARKET_L5_PAGE_MAX,
} from "@/lib/marketingUi";

const D = TT_MARKETING_MARKET_DARK_PATH;

/** 与 `/market` L5 同宽 */
export const GUIDE_DETAIL_PAGE_MAX_CLASS = TT_MARKETING_MARKET_L5_PAGE_MAX;

/** 暖金渐变外框 + 深色玻璃内胆（同源 market 列表卡） */
export const GUIDE_DETAIL_PANEL_FRAME_CLASS = TT_MARKETING_MARKET_L5_LIST_CARD_FRAME;
export const GUIDE_DETAIL_PANEL_INNER_CLASS = TT_MARKETING_MARKET_L5_LIST_CARD_INNER;
export const GUIDE_DETAIL_PANEL_CLASS = GUIDE_DETAIL_PANEL_INNER_CLASS;

export const GUIDE_DETAIL_SECTION_HEADING_CLASS =
  "px-6 pt-5 pb-3 border-b border-ref-sun/12 text-body font-semibold text-slate-100";
/** 与市场抽屉 `marketDetailDrawerMeta` 同源 · 分区小标签 */
export const GUIDE_DETAIL_SECTION_LABEL_CLASS = "text-meta text-slate-400";
export const GUIDE_DETAIL_SECTION_HEADING_META_CLASS = GUIDE_DETAIL_SECTION_LABEL_CLASS;
export const GUIDE_DETAIL_ACCENT_TEXT_CLASS = TT_MARKETING_GUIDES_ATMOSPHERE.accentText;
export const GUIDE_DETAIL_HERO_RING_CLASS = "ring-1 ring-ref-sun/22";
export const GUIDE_DETAIL_AVATAR_FALLBACK_TEXT_CLASS = TT_MARKETING_GUIDES_ATMOSPHERE.avatarFallbackText;
export const GUIDE_DETAIL_RETRY_PILL_CLASS = TT_MARKETING_BTN_MARKET_PRIMARY_PILL;
export const GUIDE_DETAIL_PRIMARY_BTN_CLASS = TT_MARKETING_BTN_MARKET_PRIMARY;
export const GUIDE_DETAIL_PRIMARY_CTA_BLOCK_CLASS = `${TT_MARKETING_BTN_MARKET_PRIMARY} w-full rounded-[var(--radius-md)] px-5 py-3 text-center text-small font-semibold`;
export const GUIDE_DETAIL_SECONDARY_BTN_CLASS = `${D.cardViewItineraryLink} w-full text-center`;
export const GUIDE_DETAIL_DID_COPY_BTN_CLASS = TT_MARKETING_GUIDES_ATMOSPHERE.didCopyBtn;
export const GUIDE_DETAIL_INPUT_FOCUS_CLASS = TT_MARKETING_GUIDES_ATMOSPHERE.inputFocus;
export const GUIDE_DETAIL_BREADCRUMB_LINK_CLASS = D.inlineLinkUnderline;
export const GUIDE_DETAIL_CROSS_NAV_LINK_CLASS = D.emptyCrossNavLink;
export const GUIDE_DETAIL_CROSS_NAV_SEP_CLASS = D.emptyCrossNavSep;
export const GUIDE_DETAIL_INNER_DIVIDER_CLASS = D.cardContentDivider;
export const GUIDE_DETAIL_INNER_SECTION_CLASS = "px-6 py-5 space-y-2";
