/**
 * `/orders` 列表 · L5 暖金产品 Console（① · 与首页 `TT_MARKETING_ACTION_*` 同源）。
 * 机读：`ordersListL5.contract.test.ts`
 */
import {
  TT_MARKETING_ACTION_STAT_EMPHASIS,
  TT_MARKETING_ACTION_TITLE_GRADIENT,
  TT_MARKETING_BTN_PRIMARY_WARM_SUBMIT,
  TT_MARKETING_CALLOUT_LEFT_ACCENT,
  TT_MARKETING_ORDERS_FOOTER_CROSS_LINK,
  TT_MARKETING_FOCUS_RING_CONSOLE,
  TT_MARKETING_ORDERS_CARD_ACTIONS_PANEL,
  TT_MARKETING_ORDERS_CARD_ESCROW_BTN,
  TT_MARKETING_ORDERS_CARD_DELETE_BTN,
  TT_MARKETING_ORDERS_CARD_PREVIEW_BTN,
  TT_MARKETING_ORDERS_COVER_RING,
  TT_MARKETING_ORDERS_EMPTY_CARD,
  TT_MARKETING_ORDERS_FILTER_BAR,
  TT_MARKETING_ORDERS_FILTER_TAB_IDLE,
  TT_MARKETING_ORDERS_FILTER_TAB_SELECTED,
  TT_MARKETING_ORDERS_LIST_CARD_FRAME,
  TT_MARKETING_ORDERS_LIST_CARD_INNER,
  TT_MARKETING_ORDERS_LIST_COUNT_BADGE,
  TT_MARKETING_ORDERS_PAGE_AMBIENT,
  TT_MARKETING_ORDERS_PAGE_VIGNETTE,
  TT_MARKETING_ORDERS_PAGE_HERO_FRAME,
  TT_MARKETING_ORDERS_PAGE_HERO_INNER,
  TT_MARKETING_ORDERS_PAGE_HERO_INNER_GLOW,
  TT_MARKETING_ORDERS_PAGE_KICKER,
  TT_MARKETING_ORDERS_PAGE_SECTION_BRIDGE_LINE,
  TT_MARKETING_ORDERS_PAGE_SHELL,
  TT_MARKETING_ORDERS_PAGE_INNER,
  TT_MARKETING_ORDERS_PAGE_TITLE,
  TT_MARKETING_ORDERS_CALLOUT_PANEL,
  TT_MARKETING_ORDERS_HERO_CTA,
  TT_MARKETING_ORDERS_FOOTER_WRAP,
  TT_MARKETING_ORDERS_FOOTER_TOP_FADE,
  TT_MARKETING_ORDERS_LOAD_MORE_BTN,
  TT_MARKETING_ORDERS_LOAD_MORE_SPINNER,
  TT_MARKETING_ORDERS_LIST_END_PANEL,
  TT_MARKETING_ORDERS_LIST_END_TEXT,
  TT_MARKETING_ORDERS_EMPTY_GLOW,
  TT_MARKETING_ORDERS_LOAD_MORE_ERROR_PANEL,
  TT_MARKETING_ORDERS_EXPECT_BANNER_PANEL,
  TT_MARKETING_ORDERS_BOOK_GUIDE_CHECKING_PANEL,
  TT_MARKETING_ORDERS_BOOK_GUIDE_INVALID_PANEL,
  TT_MARKETING_ORDERS_EMPTY_ICON,
  TT_MARKETING_ORDERS_FILTER_EMPTY_ICON,
  TT_MARKETING_ORDERS_SYNCING_BANNER,
  TT_MARKETING_ORDERS_DOT_GRID,
  TT_MARKETING_ORDERS_ACTIVE_FILTER_CHIP,
  TT_MARKETING_ORDERS_ACTIVE_FILTER_CHIP_DISMISS,
  TT_MARKETING_ORDERS_STICKY_HINT_BAR,
  TT_MARKETING_ORDERS_CARD_OPEN_CHEVRON,
  TT_MARKETING_ORDERS_STICKY_FILTER_DOCK,
  TT_MARKETING_ORDERS_STICKY_FILTER_RAIL,
  TT_MARKETING_ORDERS_FILTER_RAIL_EMBEDDED,
  TT_MARKETING_ORDERS_TOOLBAR_STICKY,
  TT_MARKETING_ORDERS_TOOLBAR_FRAME,
  TT_MARKETING_ORDERS_TOOLBAR_INNER,
  TT_MARKETING_ORDERS_TOOLBAR_SHELL,
  TT_MARKETING_ORDERS_TOOLBAR_INNER_FLAT,
  TT_MARKETING_ORDERS_HERO_SCOPE_NOTE,
  TT_MARKETING_ORDERS_HINT_BAR_SLIM,
  TT_MARKETING_ORDERS_HINT_TOGGLE_BTN,
  TT_MARKETING_ORDERS_HINT_BODY,
  TT_MARKETING_ORDERS_HINT_CHEVRON,
  TT_MARKETING_ORDERS_CARD_ACTIONS_STACK,
  TT_MARKETING_ORDERS_CARD_SECONDARY_ROW,
  TT_MARKETING_ORDERS_CARD_SECONDARY_BTN,
  TT_MARKETING_ORDERS_CARD_DELETE_BTN_COMPACT,
  TT_MARKETING_ORDERS_META_ICON,
  TT_MARKETING_ORDERS_AMOUNT_ROW,
  TT_MARKETING_ORDERS_FILTER_RAIL_LABEL,
  TT_MARKETING_ORDERS_FILTER_BAR_SCROLL,
  TT_MARKETING_ORDERS_FILTER_TAB_INDICATOR,
  TT_MARKETING_ORDERS_FILTER_TAB_ON_INDICATOR,
  TT_MARKETING_ORDERS_SEARCH_WRAP,
  TT_MARKETING_ORDERS_SEARCH_INPUT,
  TT_MARKETING_ORDERS_SEARCH_ICON,
  TT_MARKETING_ORDERS_SEARCH_CLEAR_BTN,
  TT_MARKETING_ORDERS_SEARCH_EMPTY_ICON,
  TT_MARKETING_ORDERS_SEARCH_HIGHLIGHT_MARK,
  TT_MARKETING_ORDERS_SEARCH_SCOPE_HINT,
  TT_MARKETING_ORDERS_ACTIVE_FILTERS_BAR,
  TT_MARKETING_ORDERS_ACTIVE_FILTERS_LABEL,
  TT_MARKETING_ORDERS_CLEAR_ALL_FILTERS_BTN,
  TT_MARKETING_ORDERS_SEARCH_PENDING_DOT,
  TT_MARKETING_ORDERS_CARD_SWIPE_SHELL,
  TT_MARKETING_ORDERS_CARD_SWIPE_TRAY,
  TT_MARKETING_ORDERS_CARD_SWIPE_SURFACE,
  TT_MARKETING_ORDERS_CARD_SWIPE_PREVIEW,
  TT_MARKETING_ORDERS_CARD_SWIPE_ESCROW,
  TT_MARKETING_ORDERS_CARD_SWIPE_DELETE,
  TT_MARKETING_ORDERS_CARD_SWIPE_EDGE_GLOW,
  TT_MARKETING_ORDERS_FILTER_TAB_COUNT_BADGE,
  TT_MARKETING_ORDERS_FILTER_TAB_COUNT_ON_INDICATOR,
  TT_MARKETING_ORDERS_FILTER_TAB_COUNT_BUMP,
  TT_MARKETING_ORDERS_LIST_CARD_KEYBOARD_FOCUS,
  TT_MARKETING_ORDERS_HINT_BAR,
  TT_MARKETING_ORDERS_LIST_END_ICON,
  TT_MARKETING_ORDERS_AMOUNT_VALUE,
  TT_MARKETING_ORDERS_AMOUNT_CURRENCY,
  TT_MARKETING_ORDERS_STATUS_BADGE_BASE,
  TT_MARKETING_ORDERS_MOBILE_ACTION_BAR,
  TT_MARKETING_ORDERS_CARD_DRAFT_RIBBON,
  TT_MARKETING_ORDERS_CARD_DELETING_OVERLAY,
  TT_MARKETING_ORDERS_SYNCING_PROGRESS_TRACK,
  TT_MARKETING_ORDERS_SYNCING_PROGRESS_FILL,
  TT_MARKETING_ORDERS_ALERT_DISMISS_BTN,
  TT_MARKETING_ORDERS_SKELETON_SHIMMER,
  TT_MARKETING_ORDER_STATUS_BADGE_WARM,
  TT_MARKETING_ORDERS_TEXT_BODY,
  TT_MARKETING_ORDERS_TEXT_META,
  TT_MARKETING_ORDERS_TEXT_MUTED,
} from "@/lib/marketingUi";
import { traveltrustProductL5ShellDataAttrs } from "@/lib/traveltrustHomepageFunnelL5";
import { touchTargetLink44Classes } from "@/lib/travelLinkFocus";

export const ORDERS_LIST_L5_VISUAL_DATA_ATTR = "l5" as const;

export const ORDERS_LIST_L5_SSOT_ID = "TT-ORDERS-LIST-L5-2026-05" as const;

export const ORDERS_LIST_L5_DELETE_CONFIRM_DATA_ATTR = "delete" as const;

const FILTER_TAB_BASE =
  "inline-flex min-h-[40px] items-center justify-center rounded-[var(--radius-md)] px-3.5 py-1.5 text-small font-medium transition motion-reduce:transition-none motion-sub motion-safe:active:scale-[0.98] motion-reduce:active:scale-100 focus:outline-none focus-visible:ring-2 focus-visible:ring-ref-sun/50 focus-visible:ring-offset-2 focus-visible:ring-offset-[#0c0a09]";

export const TT_ORDERS_LIST_L5 = {
  pageShell: `${TT_MARKETING_ORDERS_PAGE_SHELL} relative isolate overflow-x-clip`,
  pageVignette: TT_MARKETING_ORDERS_PAGE_VIGNETTE,
  pageInner: `${TT_MARKETING_ORDERS_PAGE_INNER} relative z-[1] pb-24 md:pb-0`,
  pageHeaderWrap: "mb-3 space-y-3",
  ambient: TT_MARKETING_ORDERS_PAGE_AMBIENT,
  dotGrid: TT_MARKETING_ORDERS_DOT_GRID,
  heroFrame: TT_MARKETING_ORDERS_PAGE_HERO_FRAME,
  heroInner: TT_MARKETING_ORDERS_PAGE_HERO_INNER,
  heroInnerGlow: TT_MARKETING_ORDERS_PAGE_HERO_INNER_GLOW,
  kicker: TT_MARKETING_ORDERS_PAGE_KICKER,
  title: TT_MARKETING_ORDERS_PAGE_TITLE,
  errorTitle: `text-h4 font-bold tracking-tight drop-shadow-landing-hero ${TT_MARKETING_ACTION_TITLE_GRADIENT}`,
  calloutAccent: TT_MARKETING_CALLOUT_LEFT_ACCENT,
  calloutPanel: TT_MARKETING_ORDERS_CALLOUT_PANEL,
  heroScopeNote: TT_MARKETING_ORDERS_HERO_SCOPE_NOTE,
  bodyText: `text-body ${TT_MARKETING_ORDERS_TEXT_BODY}`,
  metaText: `text-meta ${TT_MARKETING_ORDERS_TEXT_META}`,
  hintText: `text-meta ${TT_MARKETING_ORDERS_TEXT_BODY}`,
  panelTitle: "text-small font-semibold text-slate-50",
  panelBodyMuted: `text-meta ${TT_MARKETING_ORDERS_TEXT_META}`,
  hintSeparator: `mx-1.5 ${TT_MARKETING_ORDERS_TEXT_MUTED}`,
  warningNote: "text-meta text-amber-300/95 mt-2 leading-snug",
  deletingBadge:
    "rounded-full border border-ref-sun/35 bg-slate-950/80 px-3 py-1 text-meta font-semibold text-slate-200 shadow-soft",
  coverPlaceholder: "bg-ink-800/90",
  bridgeLine: TT_MARKETING_ORDERS_PAGE_SECTION_BRIDGE_LINE,
  filterBar: TT_MARKETING_ORDERS_FILTER_BAR,
  filterTabBase: FILTER_TAB_BASE,
  filterTabIdle: TT_MARKETING_ORDERS_FILTER_TAB_IDLE,
  filterTabSelected: TT_MARKETING_ORDERS_FILTER_TAB_SELECTED,
  heroCta: TT_MARKETING_ORDERS_HERO_CTA,
  activeFilterChip: TT_MARKETING_ORDERS_ACTIVE_FILTER_CHIP,
  activeFilterChipDismiss: TT_MARKETING_ORDERS_ACTIVE_FILTER_CHIP_DISMISS,
  stickyHintBar: TT_MARKETING_ORDERS_STICKY_HINT_BAR,
  mobileActionBar: TT_MARKETING_ORDERS_MOBILE_ACTION_BAR,
  listItemEnter: "orders-list-l5-rise",
  destinationTitle: "text-body-l font-semibold text-slate-50 truncate tracking-tight",
  destinationMeta: `text-meta ${TT_MARKETING_ORDERS_TEXT_META} mt-0.5 flex flex-wrap items-center gap-x-2 gap-y-0.5`,
  metaDestIcon: TT_MARKETING_ORDERS_META_ICON,
  metaDateIcon: TT_MARKETING_ORDERS_META_ICON,
  listCardFrame: TT_MARKETING_ORDERS_LIST_CARD_FRAME,
  listCardInner: TT_MARKETING_ORDERS_LIST_CARD_INNER,
  listCardGroup: "group",
  listCardArticle:
    "motion-safe:transition-[box-shadow] motion-safe:duration-200 group-hover:shadow-[inset_0_0_0_1px_rgba(252,164,124,0.14)] motion-reduce:transition-none",
  cardOpenChevron: TT_MARKETING_ORDERS_CARD_OPEN_CHEVRON,
  stickyFilterDock: TT_MARKETING_ORDERS_STICKY_FILTER_DOCK,
  stickyFilterRail: TT_MARKETING_ORDERS_STICKY_FILTER_RAIL,
  filterRailEmbedded: TT_MARKETING_ORDERS_FILTER_RAIL_EMBEDDED,
  toolbarSticky: TT_MARKETING_ORDERS_TOOLBAR_STICKY,
  toolbarFrame: TT_MARKETING_ORDERS_TOOLBAR_FRAME,
  toolbarInner: TT_MARKETING_ORDERS_TOOLBAR_INNER,
  toolbarShell: TT_MARKETING_ORDERS_TOOLBAR_SHELL,
  toolbarInnerFlat: TT_MARKETING_ORDERS_TOOLBAR_INNER_FLAT,
  amountRow: TT_MARKETING_ORDERS_AMOUNT_ROW,
  filterRailLabel: TT_MARKETING_ORDERS_FILTER_RAIL_LABEL,
  filterBarScroll: TT_MARKETING_ORDERS_FILTER_BAR_SCROLL,
  filterTabIndicator: TT_MARKETING_ORDERS_FILTER_TAB_INDICATOR,
  filterTabOnIndicator: TT_MARKETING_ORDERS_FILTER_TAB_ON_INDICATOR,
  searchWrap: TT_MARKETING_ORDERS_SEARCH_WRAP,
  searchInput: TT_MARKETING_ORDERS_SEARCH_INPUT,
  searchIcon: TT_MARKETING_ORDERS_SEARCH_ICON,
  searchClearBtn: TT_MARKETING_ORDERS_SEARCH_CLEAR_BTN,
  searchEmptyIcon: TT_MARKETING_ORDERS_SEARCH_EMPTY_ICON,
  searchHighlightMark: TT_MARKETING_ORDERS_SEARCH_HIGHLIGHT_MARK,
  searchScopeHint: TT_MARKETING_ORDERS_SEARCH_SCOPE_HINT,
  searchScopeHintInline: `text-meta ${TT_MARKETING_ORDERS_TEXT_META} leading-snug border-l-2 border-ref-sun/22 pl-2.5`,
  activeFiltersBar: TT_MARKETING_ORDERS_ACTIVE_FILTERS_BAR,
  activeFiltersLabel: TT_MARKETING_ORDERS_ACTIVE_FILTERS_LABEL,
  clearAllFiltersBtn: TT_MARKETING_ORDERS_CLEAR_ALL_FILTERS_BTN,
  searchPendingDot: TT_MARKETING_ORDERS_SEARCH_PENDING_DOT,
  cardSwipeShell: TT_MARKETING_ORDERS_CARD_SWIPE_SHELL,
  cardSwipeTray: TT_MARKETING_ORDERS_CARD_SWIPE_TRAY,
  cardSwipeSurface: TT_MARKETING_ORDERS_CARD_SWIPE_SURFACE,
  cardSwipePreview: TT_MARKETING_ORDERS_CARD_SWIPE_PREVIEW,
  cardSwipeEscrow: TT_MARKETING_ORDERS_CARD_SWIPE_ESCROW,
  cardSwipeDelete: TT_MARKETING_ORDERS_CARD_SWIPE_DELETE,
  cardSwipeEdgeGlow: TT_MARKETING_ORDERS_CARD_SWIPE_EDGE_GLOW,
  filterTabCountBadge: TT_MARKETING_ORDERS_FILTER_TAB_COUNT_BADGE,
  filterTabCountOnIndicator: TT_MARKETING_ORDERS_FILTER_TAB_COUNT_ON_INDICATOR,
  filterTabCountBump: TT_MARKETING_ORDERS_FILTER_TAB_COUNT_BUMP,
  listCardKeyboardFocus: TT_MARKETING_ORDERS_LIST_CARD_KEYBOARD_FOCUS,
  hintBar: `${TT_MARKETING_ORDERS_HINT_BAR} ${TT_MARKETING_CALLOUT_LEFT_ACCENT}`,
  hintBarSlim: TT_MARKETING_ORDERS_HINT_BAR_SLIM,
  hintToggle: TT_MARKETING_ORDERS_HINT_TOGGLE_BTN,
  hintChevron: TT_MARKETING_ORDERS_HINT_CHEVRON,
  hintBody: TT_MARKETING_ORDERS_HINT_BODY,
  listEndIcon: TT_MARKETING_ORDERS_LIST_END_ICON,
  cardDraftRibbon: TT_MARKETING_ORDERS_CARD_DRAFT_RIBBON,
  cardDeletingOverlay: TT_MARKETING_ORDERS_CARD_DELETING_OVERLAY,
  syncingProgressTrack: TT_MARKETING_ORDERS_SYNCING_PROGRESS_TRACK,
  syncingProgressFill: TT_MARKETING_ORDERS_SYNCING_PROGRESS_FILL,
  destinationSub: `text-meta ${TT_MARKETING_ORDERS_TEXT_META} mt-0.5 truncate`,
  coverRing: TT_MARKETING_ORDERS_COVER_RING,
  coverImage:
    "object-cover motion-safe:transition-transform motion-safe:duration-300 motion-safe:group-hover:scale-[1.04] motion-reduce:transition-none",
  cardLinkFocus: `${TT_MARKETING_FOCUS_RING_CONSOLE} focus-visible:ring-offset-[#0c0a09]`,
  cardActionsPanel: TT_MARKETING_ORDERS_CARD_ACTIONS_PANEL,
  cardActionsStack: TT_MARKETING_ORDERS_CARD_ACTIONS_STACK,
  cardSecondaryRow: TT_MARKETING_ORDERS_CARD_SECONDARY_ROW,
  cardSecondaryBtn: `${touchTargetLink44Classes} ${TT_MARKETING_ORDERS_CARD_SECONDARY_BTN}`,
  cardDeleteBtnCompact: `${touchTargetLink44Classes} ${TT_MARKETING_ORDERS_CARD_DELETE_BTN_COMPACT}`,
  cardPrimaryBtn: `${touchTargetLink44Classes} ${TT_MARKETING_BTN_PRIMARY_WARM_SUBMIT} w-full rounded-[var(--radius-md)] px-4 py-2 motion-sub motion-safe:active:scale-[0.98] motion-reduce:active:scale-100`,
  cardEscrowBtn: `${touchTargetLink44Classes} ${TT_MARKETING_ORDERS_CARD_ESCROW_BTN}`,
  cardPreviewBtn: `${touchTargetLink44Classes} ${TT_MARKETING_ORDERS_CARD_PREVIEW_BTN}`,
  cardDeleteBtn: `${touchTargetLink44Classes} ${TT_MARKETING_ORDERS_CARD_DELETE_BTN}`,
  statusBadgeWarm: TT_MARKETING_ORDER_STATUS_BADGE_WARM,
  statusBadgeNeutral: `${TT_MARKETING_ORDERS_STATUS_BADGE_BASE} bg-ink-800/80 text-slate-200 ring-1 ring-white/14`,
  statusBadgeSuccess: `${TT_MARKETING_ORDERS_STATUS_BADGE_BASE} bg-success/12 text-success ring-1 ring-success/25`,
  statusBadgeDanger: `${TT_MARKETING_ORDERS_STATUS_BADGE_BASE} bg-danger/12 text-danger ring-1 ring-danger/25`,
  amountEmphasis: TT_MARKETING_ACTION_STAT_EMPHASIS,
  amountValue: TT_MARKETING_ORDERS_AMOUNT_VALUE,
  amountCurrency: TT_MARKETING_ORDERS_AMOUNT_CURRENCY,
  statusBadgeBase: TT_MARKETING_ORDERS_STATUS_BADGE_BASE,
  listCountBadge: TT_MARKETING_ORDERS_LIST_COUNT_BADGE,
  emptyCard: TT_MARKETING_ORDERS_EMPTY_CARD,
  crossNavLink: `${touchTargetLink44Classes} ${TT_MARKETING_ORDERS_FOOTER_CROSS_LINK}`,
  crossNavSeparator: "text-slate-400",
  footerWrap: TT_MARKETING_ORDERS_FOOTER_WRAP,
  footerTopFade: TT_MARKETING_ORDERS_FOOTER_TOP_FADE,
  skeletonShimmer: TT_MARKETING_ORDERS_SKELETON_SHIMMER,
  skeletonHeroBlock: "mb-8 space-y-5",
  loadMoreBtn: `${touchTargetLink44Classes} ${TT_MARKETING_ORDERS_LOAD_MORE_BTN}`,
  loadMoreSpinner: TT_MARKETING_ORDERS_LOAD_MORE_SPINNER,
  listEndPanel: TT_MARKETING_ORDERS_LIST_END_PANEL,
  listEndText: TT_MARKETING_ORDERS_LIST_END_TEXT,
  emptyGlow: TT_MARKETING_ORDERS_EMPTY_GLOW,
  loadMoreErrorPanel: TT_MARKETING_ORDERS_LOAD_MORE_ERROR_PANEL,
  alertPanel: `mb-6 space-y-2 ${TT_MARKETING_ORDERS_LOAD_MORE_ERROR_PANEL}`,
  expectBannerPanel: `mb-6 ${TT_MARKETING_ORDERS_EXPECT_BANNER_PANEL}`,
  alertDismissBtn: `${touchTargetLink44Classes} ${TT_MARKETING_ORDERS_ALERT_DISMISS_BTN}`,
  inlineRefreshBtn: `${touchTargetLink44Classes} ${TT_MARKETING_ORDERS_LOAD_MORE_BTN} px-4 py-2`,
  bookGuideCheckingPanel: `mb-6 ${TT_MARKETING_ORDERS_BOOK_GUIDE_CHECKING_PANEL}`,
  bookGuideInvalidPanel: `mb-6 ${TT_MARKETING_ORDERS_BOOK_GUIDE_INVALID_PANEL}`,
  bookGuideValidOuter: "mb-6",
  bookGuideValidInner: `${TT_MARKETING_ORDERS_PAGE_HERO_INNER} space-y-4`,
  bookGuideCtaPrimary: `${touchTargetLink44Classes} ${TT_MARKETING_ORDERS_CARD_ESCROW_BTN} !w-auto shrink-0 px-5`,
  bookGuideCtaSecondary: `${touchTargetLink44Classes} ${TT_MARKETING_ORDERS_CARD_PREVIEW_BTN} !w-auto shrink-0 px-5`,
  emptyIcon: TT_MARKETING_ORDERS_EMPTY_ICON,
  filterEmptyIcon: TT_MARKETING_ORDERS_FILTER_EMPTY_ICON,
  syncingBanner: TT_MARKETING_ORDERS_SYNCING_BANNER,
  cardActionsPanelMobile: `${TT_MARKETING_ORDERS_CARD_ACTIONS_PANEL} w-full sm:w-auto`,
  emptySecondaryBtn: `${touchTargetLink44Classes} ${TT_MARKETING_ORDERS_CARD_PREVIEW_BTN}`,
  errorShell: `${TT_MARKETING_ORDERS_PAGE_SHELL} relative isolate flex min-h-[50vh] items-center justify-center overflow-x-clip p-8`,
  deleteConfirmOverlay:
    "fixed inset-0 z-[120] flex items-center justify-center bg-black/70 px-4 py-8 backdrop-blur-sm motion-safe:animate-in motion-safe:fade-in duration-200",
  deleteConfirmPanel:
    "relative w-full max-w-md rounded-[var(--radius-lg)] border border-ref-sun/35 bg-[#0c0a09]/95 p-5 shadow-[0_0_40px_rgba(251,191,36,0.08)] ring-1 ring-ref-sun/20 sm:p-6",
  deleteConfirmTitle: "text-body font-semibold text-slate-100",
  deleteConfirmDesc: "mt-2 text-meta leading-snug text-slate-300/95",
  deleteConfirmActions: "mt-5 flex flex-wrap gap-3",
  deleteConfirmBtnCancel: `${touchTargetLink44Classes} inline-flex min-h-[44px] flex-1 items-center justify-center rounded-[var(--radius-md)] border border-white/14 bg-slate-950/60 px-4 py-2 text-small font-medium text-slate-200 hover:border-ref-sun/35 hover:bg-slate-900/80 motion-sub focus:outline-none focus-visible:ring-2 focus-visible:ring-ref-sun/50 focus-visible:ring-offset-2 focus-visible:ring-offset-[#0c0a09] disabled:cursor-not-allowed disabled:opacity-50`,
  deleteConfirmBtnDanger: `${touchTargetLink44Classes} inline-flex min-h-[44px] flex-1 items-center justify-center rounded-[var(--radius-md)] border border-danger/55 bg-danger/10 px-4 py-2 text-small font-semibold text-red-300 hover:border-danger/70 hover:bg-danger/16 hover:text-red-200 motion-sub focus:outline-none focus-visible:ring-2 focus-visible:ring-danger/55 focus-visible:ring-offset-2 focus-visible:ring-offset-[#0c0a09] disabled:cursor-not-allowed disabled:opacity-50`,
} as const;

/** 列表卡片入场 stagger（ms · 上限 420） */
export function ordersListL5ListItemStaggerMs(index: number): number {
  return Math.min(index * 70, 420);
}

export function ordersListL5MainDataAttrs(): Record<string, string> {
  return {
    ...traveltrustProductL5ShellDataAttrs("orders"),
    "data-tt-orders-list-l5": ORDERS_LIST_L5_VISUAL_DATA_ATTR,
    "data-tt-orders-list-l5-ssot": ORDERS_LIST_L5_SSOT_ID,
  };
}
