/**
 * P29：向导栏空列表时国际示例（与 `MOCK_GUIDES` 分离）
 */

import type { GuideCardItem } from "@/lib/marketTypes";
import { DEFAULT_SETTLEMENT_CURRENCY_CODE } from "@/lib/defaultSettlementCurrency";
import { GUIDE_AVATARS } from "./guides";

/**
 * 向导栏空列表时示例：多城市 × 独立头像与简介（封面图走 `GUIDE_AVATARS` / 订单走 `ORDER_IMAGES`，减少灰块）。
 * 与 `MOCK_GUIDES` 分离，避免覆盖国内筛选演示数据。
 */
export const MARKET_GUIDE_SHOWCASE: GuideCardItem[] = [
  {
    id: "tt-showcase-guide-tokyo",
    user_id: "u-showcase-jp-tokyo",
    city: "东京",
    country_code: "JP",
    languages: ["中文", "日本語", "English"],
    service_types: ["向导服务", "摄影服务"],
    bio: "在住 8 年，熟渋谷·浅草·富士日帰り与和食预约。可中日英三语，擅长亲子与摄影机位规划。",
    stake_amount: "1200",
    hourly_rate: "68",
    hourly_currency: DEFAULT_SETTLEMENT_CURRENCY_CODE,
    avatar_url: GUIDE_AVATARS["mock-guide-1"],
    rating: 4.9,
    completedCount: 127,
    responseSLA: "<2h",
    priceRange: { guideFeePerDay: 520, carFeePerDay: 180 },
    status: "active",
    created_at: "2024-03-12T09:00:00Z",
  },
  {
    id: "tt-showcase-guide-bangkok",
    user_id: "u-showcase-th-bkk",
    city: "曼谷",
    country_code: "TH",
    languages: ["中文", "English", "ไทย"],
    service_types: ["向导服务", "陪玩服务"],
    bio: "本地通：大皇宫、水上市场、米其林路边摊与夜游船。可安排 SPA 与素万那普接机错峰。",
    stake_amount: "480",
    hourly_rate: "38",
    hourly_currency: DEFAULT_SETTLEMENT_CURRENCY_CODE,
    avatar_url: GUIDE_AVATARS["mock-guide-2"],
    rating: 4.8,
    completedCount: 89,
    responseSLA: "<3h",
    status: "active",
    created_at: "2024-04-01T11:20:00Z",
  },
  {
    id: "tt-showcase-guide-paris",
    user_id: "u-showcase-fr-paris",
    city: "巴黎",
    country_code: "FR",
    languages: ["Français", "中文", "English"],
    service_types: ["向导服务", "摄影服务"],
    bio: "艺术史背景：卢浮宫、奥赛、玛黑区散步与塞纳河黄昏。可代订时段票与小众画廊。",
    stake_amount: "950",
    hourly_rate: "72",
    hourly_currency: DEFAULT_SETTLEMENT_CURRENCY_CODE,
    avatar_url: GUIDE_AVATARS["mock-guide-3"],
    rating: 4.95,
    completedCount: 64,
    responseSLA: "<4h",
    status: "active",
    created_at: "2024-02-18T14:00:00Z",
  },
  {
    id: "tt-showcase-guide-nyc",
    user_id: "u-showcase-us-nyc",
    city: "纽约",
    country_code: "US",
    languages: ["English", "中文"],
    service_types: ["向导服务", "司机服务"],
    bio: "曼哈顿中城、DUMBO、博物馆日与纽新机场接送。熟悉音乐剧排期与无车步行动线。",
    stake_amount: "1500",
    hourly_rate: "85",
    hourly_currency: DEFAULT_SETTLEMENT_CURRENCY_CODE,
    avatar_url: GUIDE_AVATARS["mock-guide-4"],
    rating: 4.85,
    completedCount: 41,
    responseSLA: "<6h",
    status: "active",
    created_at: "2024-05-05T16:30:00Z",
  },
  {
    id: "tt-showcase-guide-sydney",
    user_id: "u-showcase-au-syd",
    city: "悉尼",
    country_code: "AU",
    languages: ["English", "中文"],
    service_types: ["向导服务", "陪玩服务", "摄影服务"],
    bio: "邦迪日出、歌剧院内导览、蓝山一日与猎人谷酒庄。可安排家庭友好节奏与儿童推车路线。",
    stake_amount: "720",
    hourly_rate: "58",
    hourly_currency: DEFAULT_SETTLEMENT_CURRENCY_CODE,
    avatar_url: GUIDE_AVATARS["mock-guide-5"],
    rating: 4.9,
    completedCount: 73,
    responseSLA: "<3h",
    priceRange: { guideFeePerDay: 480, carFeePerDay: 220 },
    status: "active",
    created_at: "2024-01-28T08:15:00Z",
  },
  {
    id: "tt-showcase-guide-queenstown",
    user_id: "u-showcase-nz-qtn",
    city: "皇后镇",
    country_code: "NZ",
    languages: ["中文", "English"],
    service_types: ["向导服务", "摄影服务", "司机服务"],
    bio: "南岛中线 10 年：基督城进 · 特卡波观星 · 库克山轻徒步 · 米尔福德峡湾一日船游。熟悉旺季车位与峡湾晴雨备选线。",
    stake_amount: "1100",
    hourly_rate: "78",
    hourly_currency: DEFAULT_SETTLEMENT_CURRENCY_CODE,
    avatar_url: GUIDE_AVATARS["mock-guide-9"],
    rating: 4.92,
    completedCount: 56,
    responseSLA: "<4h",
    priceRange: { guideFeePerDay: 620, carFeePerDay: 260 },
    status: "active",
    created_at: "2024-03-20T07:00:00Z",
  },
  {
    id: "tt-showcase-guide-reykjavik",
    user_id: "u-showcase-is-rkv",
    city: "雷克雅未克",
    country_code: "IS",
    languages: ["English", "中文", "Íslenska"],
    service_types: ["向导服务", "司机服务"],
    bio: "本地执照向导：黄金圈南岸、冰川蓝冰洞季、极光夜追（看指数与云层）。可代订蓝湖时段与租车衔接。",
    stake_amount: "980",
    hourly_rate: "92",
    hourly_currency: DEFAULT_SETTLEMENT_CURRENCY_CODE,
    avatar_url: GUIDE_AVATARS["mock-guide-10"],
    rating: 4.88,
    completedCount: 34,
    responseSLA: "<6h",
    status: "active",
    created_at: "2024-02-02T12:40:00Z",
  },
  {
    id: "tt-showcase-guide-rome",
    user_id: "u-showcase-it-rom",
    city: "罗马",
    country_code: "IT",
    languages: ["Italiano", "中文", "English"],
    service_types: ["向导服务", "摄影服务"],
    bio: "艺术史硕士：斗兽场地下层、梵蒂冈博物馆动线、博尔盖塞美术馆预约。擅长避开旅行团高峰时段与城区步行衔接。",
    stake_amount: "880",
    hourly_rate: "70",
    hourly_currency: DEFAULT_SETTLEMENT_CURRENCY_CODE,
    avatar_url: GUIDE_AVATARS["mock-guide-11"],
    rating: 4.93,
    completedCount: 102,
    responseSLA: "<3h",
    priceRange: { guideFeePerDay: 540, carFeePerDay: 0 },
    status: "active",
    created_at: "2024-01-10T15:20:00Z",
  },
  {
    id: "tt-showcase-guide-seoul",
    user_id: "u-showcase-kr-sel",
    city: "首尔",
    country_code: "KR",
    languages: ["한국어", "中文", "English"],
    service_types: ["向导服务", "陪玩服务", "摄影服务"],
    bio: "弘大·圣水·汉南洞咖啡与买手店动线，景福宫韩服体验与南山夜景。可订米其林韩牛与 K-pop 场馆周边错峰。",
    stake_amount: "560",
    hourly_rate: "48",
    hourly_currency: DEFAULT_SETTLEMENT_CURRENCY_CODE,
    avatar_url: GUIDE_AVATARS["mock-guide-12"],
    rating: 4.86,
    completedCount: 118,
    responseSLA: "<2h",
    status: "active",
    created_at: "2024-04-18T10:05:00Z",
  },
];
