/**
 * P29：`/market` 示例行程（内嵌 itinerary，详情抽屉不触发 GET order）
 */

import type { OrderCardItem } from "@/lib/marketTypes";
import { ORDER_IMAGES, showcaseOrder } from "./helpers";

export const MARKET_TRAVEL_SHOWCASE_ORDERS: OrderCardItem[] = [
  showcaseOrder({
    id: "tt-showcase-jp-hokkaido",
    destination: "日本 · 北海道冰雪与温泉",
    country: "日本",
    city: "札幌",
    days: 5,
    amount: "2450",
    /** 与 MOCK_ORDERS 同源图床，避免个别 Unsplash 资源失效导致封面白块 */
    image: ORDER_IMAGES["mock-order-7"],
    breakdown: { hotel: 920, food: 480, tickets: 360, guideFee: 590, carFee: 100 },
    highlights: ["小樽运河", "登别温泉", "滑雪半日"],
    lines: [
      "新千岁机场接机 · 狸小路夜景与汤咖喱",
      "小樽运河 · 音乐盒堂 · 天狗山展望",
      "二世谷或喜乐乐滑雪体验 · 温泉旅馆一泊",
      "登别地狱谷 · 熊牧场 · 洞爷湖环湖",
      "札幌白色恋人公园 · 机场送机",
    ],
  }),
  showcaseOrder({
    id: "tt-showcase-it-rome-amalfi",
    destination: "意大利 · 罗马与阿马尔菲海岸",
    country: "意大利",
    city: "罗马",
    days: 7,
    amount: "4280",
    image: ORDER_IMAGES["mock-showcase-it"],
    breakdown: { hotel: 1680, food: 820, tickets: 640, guideFee: 890, carFee: 250 },
    transportLegs: [
      { from: "罗马", to: "那不勒斯", type: "rail" },
      { from: "索伦托", to: "波西塔诺", type: "vehicle" },
    ],
    highlights: ["斗兽场", "梵蒂冈", "阿马尔菲海岸线"],
    lines: [
      { city: "罗马", description: "罗马斗兽场 · 古罗马广场 · 威尼斯广场" },
      { city: "罗马", description: "梵蒂冈博物馆与圣彼得大教堂（预约时段）" },
      { city: "罗马", description: "特莱维喷泉 · 西班牙台阶 · 万神殿" },
      { city: "那不勒斯", description: "高铁至那不勒斯 · 庞贝古城遗址" },
      { city: "波西塔诺", description: "阿马尔菲海岸公路 · 波西塔诺小镇漫步" },
      { city: "卡普里", description: "卡普里岛一日游（蓝洞视海况）" },
      { city: "索伦托", description: "索伦托柠檬园 · 高铁返程罗马" },
    ],
  }),
  showcaseOrder({
    id: "tt-showcase-is-iceland",
    destination: "冰岛 · 黄金圈与南岸极光",
    country: "冰岛",
    city: "雷克雅未克",
    days: 4,
    amount: "3120",
    image: ORDER_IMAGES["mock-showcase-is"],
    breakdown: { hotel: 1180, food: 420, tickets: 380, guideFee: 980, carFee: 160 },
    highlights: ["间歇泉", "黑沙滩", "极光追踪"],
    lines: [
      "凯夫拉维克接机 · 蓝湖温泉（可改至离境日）",
      "黄金圈：辛格维利尔 · 盖歇尔间歇泉 · 黄金瀑布",
      "南岸：塞里雅兰瀑布 · 斯科加瀑布 · 维克黑沙滩",
      "杰古沙龙冰河湖游船 · 钻石沙滩 · 返程雷市",
    ],
  }),
  showcaseOrder({
    id: "tt-showcase-th-phuket",
    destination: "泰国 · 普吉与攀牙湾",
    country: "泰国",
    city: "普吉",
    days: 6,
    amount: "1890",
    image: ORDER_IMAGES["mock-showcase-th"],
    breakdown: { hotel: 660, food: 380, tickets: 220, guideFee: 520, carFee: 110 },
    highlights: ["出海跳岛", "老镇美食", "SPA"],
    lines: [
      "芭东或卡塔海滩休整 · 周末夜市",
      "皮皮岛 / 玛雅湾出海一日游",
      "攀牙湾皮划艇穿洞 · 007岛远眺",
      "普吉老镇葡式建筑 · 山顶大佛日落",
      "查龙寺 · 拉威海鲜市场",
      "送机前半天自由活动或 SPA",
    ],
  }),
  showcaseOrder({
    id: "tt-showcase-fr-paris",
    destination: "法国 · 巴黎艺术与左岸",
    country: "法国",
    city: "巴黎",
    days: 3,
    amount: "1680",
    image: ORDER_IMAGES["mock-showcase-fr"],
    breakdown: { hotel: 720, food: 340, tickets: 280, guideFee: 300, misc: 40 },
    highlights: ["卢浮宫", "塞纳河游船", "蒙马特"],
    lines: [
      "卢浮宫深度导览 · 杜乐丽花园",
      "奥赛博物馆 · 塞纳河黄昏游船",
      "蒙马特圣心堂 · 爱墙 · 左岸咖啡与送机",
    ],
  }),
  showcaseOrder({
    id: "tt-showcase-nz-south",
    destination: "新西兰 · 南岛中线湖光山色",
    country: "新西兰",
    city: "皇后镇",
    days: 8,
    amount: "4860",
    image: ORDER_IMAGES["mock-showcase-nz"],
    breakdown: { hotel: 1920, food: 680, tickets: 520, guideFee: 1420, carFee: 320 },
    transportLegs: [{ from: "基督城", to: "特卡波湖", type: "vehicle" }],
    highlights: ["米尔福德峡湾", "特卡波星空", "皇后镇冒险"],
    lines: [
      { city: "基督城", description: "接机 · 雅芳河与纸教堂" },
      { city: "特卡波湖", description: "普卡基湖沿途 · 好牧羊人教堂 · 暗夜观星" },
      { city: "库克山", description: "普卡基湖晨光 · 库克山步道轻徒步" },
      { city: "瓦纳卡", description: "孤独的树 · 箭镇淘金史漫步" },
      { city: "皇后镇", description: "天际缆车 · 湖滨步道与湖畔晚餐" },
      { city: "米尔福德峡湾", description: "全天峡湾游船 · 镜湖与瀑布群" },
      { city: "格林诺奇", description: "魔戒取景公路 · 天堂镇草甸" },
      { city: "皇后镇", description: "自由活动 · 送机（或改基督城离境）" },
    ],
  }),
];
