"use client";

import RegisterTouristForm from "./RegisterTouristForm";
import RegisterGuideForm from "./RegisterGuideForm";
import { useRegisterPage } from "./useRegisterPage";

export function RegisterPageMain() {
  const {
    t,
    registerType,
    loginHref,
    email,
    setEmail,
    verificationCode,
    setVerificationCode,
    sendCodeBusy,
    sendCodeCooldown,
    devCodeHint,
    handleSendVerificationCode,
    password,
    setPassword,
    passwordConfirm,
    setPasswordConfirm,
    nickname,
    setNickname,
    defaultWallet,
    setDefaultWallet,
    realName,
    setRealName,
    idNumber,
    setIdNumber,
    walletAddress,
    setWalletAddress,
    city,
    setCity,
    countryCode,
    setCountryCode,
    languages,
    setLanguages,
    serviceTypes,
    setServiceTypes,
    bio,
    setBio,
    idPhotoFile,
    setIdPhotoFile,
    languageCertFile,
    setLanguageCertFile,
    agreePrivacy,
    setAgreePrivacy,
    error,
    loading,
    handleTravelerSubmit,
    handleGuideSubmit,
    getErrorDisplay,
    inputClass,
    textareaClass,
    labelClass,
    goBackFromStep,
    registerPageShellClass,
    referralPrefill,
    referralValidateState,
  } = useRegisterPage();

  const referralProps = {
    referralPrefill,
    referralValidateState,
  };

  if (registerType === "traveler") {
    return (
      <RegisterTouristForm
        mainClassName={registerPageShellClass()}
        backdropKind="traveler"
        loginHref={loginHref}
        email={email}
        setEmail={setEmail}
        verificationCode={verificationCode}
        setVerificationCode={setVerificationCode}
        sendCodeBusy={sendCodeBusy}
        sendCodeCooldown={sendCodeCooldown}
        devCodeHint={devCodeHint}
        onSendVerificationCode={handleSendVerificationCode}
        nickname={nickname}
        setNickname={setNickname}
        password={password}
        setPassword={setPassword}
        passwordConfirm={passwordConfirm}
        setPasswordConfirm={setPasswordConfirm}
        defaultWallet={defaultWallet}
        setDefaultWallet={setDefaultWallet}
        error={error}
        loading={loading}
        onBack={goBackFromStep}
        onSubmit={handleTravelerSubmit}
        getErrorDisplay={getErrorDisplay}
        t={t}
        inputClass={inputClass}
        labelClass={labelClass}
        {...referralProps}
      />
    );
  }

  if (registerType === "provider") {
    return (
      <RegisterTouristForm
        mainClassName={registerPageShellClass()}
        backdropKind="provider"
        headingKey="auth_register_provider"
        bannerKey="auth_register_providerBanner"
        submitLabelKey="auth_register_submitProviderContinue"
        providerProgressStep={1}
        loginHref={loginHref}
        email={email}
        setEmail={setEmail}
        verificationCode={verificationCode}
        setVerificationCode={setVerificationCode}
        sendCodeBusy={sendCodeBusy}
        sendCodeCooldown={sendCodeCooldown}
        devCodeHint={devCodeHint}
        onSendVerificationCode={handleSendVerificationCode}
        nickname={nickname}
        setNickname={setNickname}
        password={password}
        setPassword={setPassword}
        passwordConfirm={passwordConfirm}
        setPasswordConfirm={setPasswordConfirm}
        defaultWallet={defaultWallet}
        setDefaultWallet={setDefaultWallet}
        error={error}
        loading={loading}
        onBack={goBackFromStep}
        onSubmit={handleTravelerSubmit}
        getErrorDisplay={getErrorDisplay}
        t={t}
        inputClass={inputClass}
        labelClass={labelClass}
        {...referralProps}
      />
    );
  }

  if (registerType === "steward") {
    return (
      <RegisterTouristForm
        mainClassName={registerPageShellClass()}
        backdropKind="steward"
        headingKey="auth_register_steward"
        bannerKey="auth_register_stewardBanner"
        loginHref={loginHref}
        email={email}
        setEmail={setEmail}
        verificationCode={verificationCode}
        setVerificationCode={setVerificationCode}
        sendCodeBusy={sendCodeBusy}
        sendCodeCooldown={sendCodeCooldown}
        devCodeHint={devCodeHint}
        onSendVerificationCode={handleSendVerificationCode}
        nickname={nickname}
        setNickname={setNickname}
        password={password}
        setPassword={setPassword}
        passwordConfirm={passwordConfirm}
        setPasswordConfirm={setPasswordConfirm}
        defaultWallet={defaultWallet}
        setDefaultWallet={setDefaultWallet}
        error={error}
        loading={loading}
        onBack={goBackFromStep}
        onSubmit={handleTravelerSubmit}
        getErrorDisplay={getErrorDisplay}
        t={t}
        inputClass={inputClass}
        labelClass={labelClass}
        {...referralProps}
      />
    );
  }

  if (registerType === "acquisition") {
    return (
      <RegisterTouristForm
        mainClassName={registerPageShellClass()}
        backdropKind="acquisition"
        headingKey="auth_register_acquisition"
        bannerKey="auth_register_acquisitionBanner"
        loginHref={loginHref}
        email={email}
        setEmail={setEmail}
        verificationCode={verificationCode}
        setVerificationCode={setVerificationCode}
        sendCodeBusy={sendCodeBusy}
        sendCodeCooldown={sendCodeCooldown}
        devCodeHint={devCodeHint}
        onSendVerificationCode={handleSendVerificationCode}
        nickname={nickname}
        setNickname={setNickname}
        password={password}
        setPassword={setPassword}
        passwordConfirm={passwordConfirm}
        setPasswordConfirm={setPasswordConfirm}
        defaultWallet={defaultWallet}
        setDefaultWallet={setDefaultWallet}
        error={error}
        loading={loading}
        onBack={goBackFromStep}
        onSubmit={handleTravelerSubmit}
        getErrorDisplay={getErrorDisplay}
        t={t}
        inputClass={inputClass}
        labelClass={labelClass}
        {...referralProps}
      />
    );
  }

  return (
    <RegisterGuideForm
      mainClassName={registerPageShellClass("guideForm")}
      backdropKind="guide"
      loginHref={loginHref}
      email={email}
      setEmail={setEmail}
      verificationCode={verificationCode}
      setVerificationCode={setVerificationCode}
      sendCodeBusy={sendCodeBusy}
      sendCodeCooldown={sendCodeCooldown}
      devCodeHint={devCodeHint}
      onSendVerificationCode={handleSendVerificationCode}
      nickname={nickname}
      setNickname={setNickname}
      password={password}
      setPassword={setPassword}
      passwordConfirm={passwordConfirm}
      setPasswordConfirm={setPasswordConfirm}
      realName={realName}
      setRealName={setRealName}
      idNumber={idNumber}
      setIdNumber={setIdNumber}
      walletAddress={walletAddress}
      setWalletAddress={setWalletAddress}
      city={city}
      setCity={setCity}
      countryCode={countryCode}
      setCountryCode={setCountryCode}
      languages={languages}
      setLanguages={setLanguages}
      serviceTypes={serviceTypes}
      setServiceTypes={setServiceTypes}
      bio={bio}
      setBio={setBio}
      idPhotoFile={idPhotoFile}
      setIdPhotoFile={setIdPhotoFile}
      languageCertFile={languageCertFile}
      setLanguageCertFile={setLanguageCertFile}
      agreePrivacy={agreePrivacy}
      setAgreePrivacy={setAgreePrivacy}
      error={error}
      loading={loading}
      onBack={goBackFromStep}
      onSubmit={handleGuideSubmit}
      getErrorDisplay={getErrorDisplay}
      t={t}
      inputClass={inputClass}
      textareaClass={textareaClass}
      labelClass={labelClass}
    />
  );
}
