import type { FormEvent } from "react";
import type { RegisterVisualKind } from "./registerBackgrounds";

export type RegisterGuideFormProps = {
  mainClassName?: string;
  backdropKind?: Exclude<RegisterVisualKind, "default">;
  loginHref: string;
  /** 进入本步时聚焦账号区邮箱 */
  autoFocusAccountEmail?: boolean;
  email: string;
  setEmail: (v: string) => void;
  nickname: string;
  setNickname: (v: string) => void;
  password: string;
  setPassword: (v: string) => void;
  passwordConfirm: string;
  setPasswordConfirm: (v: string) => void;
  realName: string;
  setRealName: (v: string) => void;
  idNumber: string;
  setIdNumber: (v: string) => void;
  walletAddress: string;
  setWalletAddress: (v: string) => void;
  city: string;
  setCity: (v: string) => void;
  countryCode: string;
  setCountryCode: (v: string) => void;
  languages: string;
  setLanguages: (v: string) => void;
  serviceTypes: string;
  setServiceTypes: (v: string) => void;
  bio: string;
  setBio: (v: string) => void;
  idPhotoFile: File | null;
  setIdPhotoFile: (f: File | null) => void;
  languageCertFile: File | null;
  setLanguageCertFile: (f: File | null) => void;
  agreePrivacy: boolean;
  setAgreePrivacy: (v: boolean) => void;
  error: string | null;
  loading: boolean;
  onBack: () => void;
  onSubmit: (e: FormEvent) => void;
  getErrorDisplay: (err: string | null) => string | null;
  t: (key: string) => string;
  inputClass: string;
  textareaClass: string;
  labelClass: string;
};
