//! 业务库读写：users / sessions / guides / orders / reviews / disputes / itineraries / order_messages（04 §四、48 §六）
//! 当 DATABASE_URL 设置时：启动时从 DB hydrate 到 chain_off 内存；注册/登录/向导/订单/评价/争议/行程/聊天双写 DB。

#![allow(dead_code, unused_imports)]

pub use admin::*;
pub use admin_console_roles::*;
pub use admin_totp::*;
pub use admin_policies_tenants::*;
pub use api_versions::*;
pub use community::*;
pub use ugc_translations::*;
pub use community_governance_audit::*;
pub use community_media_assets::*;
pub use platform_media_assets::*;
pub use community_moderation_cases::*;
pub use community_penalties::*;
pub use community_reports::*;
pub use compliance_internal_tools::*;
pub use config_center::*;
pub use correction_executor_audit::*;
pub use disputes::*;
pub use economic_aggregate::*;
pub use event_log::*;
pub use evidence::*;
pub use fee_router_events::*;
pub use governance::*;
pub use governance_proposals_projection::*;
pub use guides::*;
mod guide_exit;
pub use guide_exit::*;
pub use idempotency::*;
pub use investor_share::*;
pub use investor_stake::*;
pub use investor_lock::*;
pub use investor_distribution::*;
pub use itineraries::*;
pub use itinerary_custom_drafts::*;
pub use jobs_scheduler_config::*;
pub use lifecycle_state_machines::*;
pub use media_signed_url::*;
pub use messages::*;
mod market_listing_drafts;
mod market_listings;
mod acquisition_trust;
mod onboarding;
mod role_identity;
pub use market_listing_drafts::*;
pub use market_listings::*;
pub use acquisition_trust::*;
pub use onboarding::*;
pub use role_identity::*;
mod migrate_embed;
pub use migrate_embed::apply_api_migrations;
pub use multi_table_chain_observability::multi_table_chain_id_footprint_matrix_rows;
pub use orders::*;
pub use orders_projection::*;
mod public_catalog_surface;
pub use public_catalog_surface::*;
pub use p5_country_ledger::*;
pub use country_pool_net_profit::*;
pub use vacancy_ledger_projection::*;
pub use reconciliation_reports::*;
pub use region_vault_events::*;
pub use settlement_router_events::*;
pub use stake_lock_projection_block_lag_obs::STAKE_LOCK_PROJECTION_BLOCK_LAG_OBS_ANCHOR;
#[allow(unused_imports)] // B-115-1：HTTP/indexer 未接线前仅单测直引模块；保留与 `crate::db::*` 同形 re-export
pub use region_snapshot::*;
pub use reviews::*;
pub use trust_growth::*;
pub use users_sessions::*;
mod profile_avatar_presign_pending;
pub use profile_avatar_presign_pending::*;

mod catalog;
pub use catalog::*;
mod catalog_admin;
pub use catalog_admin::*;
mod catalog_poi_media_admin;
pub use catalog_poi_media_admin::*;
mod catalog_ops_admin;
pub use catalog_ops_admin::*;
mod catalog_revision_ops_admin;
mod catalog_geo_validation_ops_admin;
mod cms_announcements;
mod cms_roadmap;
mod ops_official_accounts_admin;
mod ops_official_guide_posts_admin;
mod ops_official_itinerary_templates_admin;
mod ops_cold_start_campaigns_admin;
mod ops_cold_start_campaigns_consumer;
pub use catalog_revision_ops_admin::*;
pub use catalog_geo_validation_ops_admin::*;
pub use cms_announcements::*;
pub use cms_roadmap::*;
pub use ops_official_accounts_admin::*;
pub use ops_official_guide_posts_admin::*;
pub use ops_official_itinerary_templates_admin::*;
pub use ops_cold_start_campaigns_admin::*;
pub use ops_cold_start_campaigns_consumer::get_deployed_cold_start_campaign_for_surface;
mod growth_referral;
pub use growth_referral::*;
mod growth_ledger;
pub use growth_ledger::*;
mod growth_observer;
pub use growth_observer::*;
mod early_bird;
pub use early_bird::*;
mod growth_fraud_ops;
pub use growth_fraud_ops::*;
mod growth_fraud_scan;
pub use growth_fraud_scan::*;
mod country_market_launch_ops;
pub use country_market_launch_ops::*;
mod region_share_reconcile_ops;
pub use region_share_reconcile_ops::*;
mod airdrop_ops;
pub use airdrop_ops::*;
mod growth_analytics_ops;
pub use growth_analytics_ops::*;
mod me_referrals;
pub use me_referrals::*;
mod admin;
mod admin_console_roles;
mod admin_totp;
mod admin_policies_tenants;
mod api_versions;
mod community;
mod ugc_translations;
mod community_governance_audit;
mod community_media_assets;
mod platform_media_assets;
mod community_moderation_cases;
mod community_penalties;
mod community_reports;
mod compliance_internal_tools;
mod config_center;
mod correction_executor_audit;
mod disputes;
mod economic_aggregate;
mod event_log;
mod evidence;
mod fee_router_events;
mod governance;
mod governance_proposals_projection;
mod guides;
mod idempotency;
mod investor_share;
mod investor_stake;
mod investor_lock;
mod investor_distribution;
mod itineraries;
mod itinerary_custom_drafts;
mod jobs_scheduler_config;
mod lifecycle_state_machines;
mod media_signed_url;
mod messages;
mod multi_table_chain_observability;
mod orders;
mod orders_projection;
mod p5_country_ledger;
mod country_pool_net_profit;
mod vacancy_ledger_projection;
mod reconciliation_reports;
mod region_vault_events;
mod settlement_router_events;
mod stake_lock_projection_block_lag_obs;
mod region_snapshot;
mod reviews;
mod trust_growth;
mod users_sessions;
mod did_rank_market_boards;
mod did_rank_snapshots;
mod market_travel_bookmarks;
mod wallet_verify_challenges;
mod auth_audit_events;
mod auth_email_tokens;
mod auth_email_send_window_events;
mod seed_community_public_showcase;
mod seed_market_public_showcase;
mod user_security_notifications;
mod governed_community_posts;
mod governed_market;
mod governed_campaign;
mod market_catalog;
mod campaign_catalog;
mod pg_transient_retry;
mod public_operations_policy;
mod public_operations_display_admin;
mod public_operations_display_history;
mod public_operations_campaigns;
pub use did_rank_market_boards::*;
pub use user_security_notifications::*;
pub use did_rank_snapshots::*;
pub use market_travel_bookmarks::*;
pub use wallet_verify_challenges::*;
pub use auth_audit_events::*;
pub use auth_email_tokens::*;
pub use auth_email_send_window_events::*;
pub use seed_community_public_showcase::*;
pub use seed_market_public_showcase::*;
pub use governed_community_posts::*;
pub use governed_market::*;
pub use governed_campaign::*;
pub use market_catalog::*;
pub use campaign_catalog::{
    get_governed_campaign_for_surface, ConsumerColdStartCampaign, ConsumerColdStartItem,
};
pub use pg_transient_retry::*;
pub use public_operations_policy::*;
pub use public_operations_display_admin::*;
pub use public_operations_display_history::*;
pub use public_operations_campaigns::*;

#[cfg(test)]
#[path = "role_identity_dual_write_db_api_tests.rs"]
mod role_identity_dual_write_db_api_tests;

#[cfg(test)]
#[path = "phase15_identity_s1_s4_db_api_tests.rs"]
mod phase15_identity_s1_s4_db_api_tests;
