-- Protocol Convergence P2: governance lifecycle state machine registry seeds (state-machine.v1 §0)

INSERT INTO lifecycle_state_machines (
    machine_code,
    domain,
    version,
    entity_type,
    current_state,
    expected_state,
    anomaly_flag,
    anomaly_type,
    last_transition_at,
    source_of_truth,
    repairable
) VALUES
    (
        'steward_application',
        'governance',
        '1.0.0',
        'steward_application',
        'doc_registry',
        'doc_registry',
        false,
        NULL,
        NULL,
        'docs/spec/governance-token/state-machine.v1.md',
        false
    ),
    (
        'steward_seat',
        'governance',
        '1.0.0',
        'region_seat',
        'doc_registry',
        'doc_registry',
        false,
        NULL,
        NULL,
        'docs/spec/governance-token/state-machine.v1.md',
        false
    ),
    (
        'country_jurisdiction',
        'governance',
        '1.0.0',
        'jurisdiction',
        'doc_registry',
        'doc_registry',
        false,
        NULL,
        NULL,
        'docs/spec/governance-token/state-machine.v1.md',
        false
    ),
    (
        'country_pool_redemption',
        'governance',
        '1.0.0',
        'pool_redemption_request',
        'doc_registry',
        'doc_registry',
        false,
        NULL,
        NULL,
        'docs/spec/governance-token/state-machine.v1.md',
        false
    ),
    (
        'region_share_eligibility',
        'governance',
        '1.0.0',
        'region_share_position',
        'doc_registry',
        'doc_registry',
        false,
        NULL,
        NULL,
        'docs/spec/governance-token/state-machine.v1.md',
        false
    )
ON CONFLICT (machine_code) DO NOTHING;
