-- Protocol lane · CMS seed (SSOT slugs align with static catalog + Admin CRUD)

INSERT INTO cms_public_announcements (
    slug, lane, kind, content_tier, publish_status, pinned, sort_order,
    title_zh, title_en, summary_zh, summary_en,
    effective_at, cta_kind, cta_href, network_scope, message_key, published_at
) VALUES
(
    'phase3-entry-mainnet-prep',
    'protocol_status',
    'product',
    'live',
    'published',
    true,
    100,
    '主网发布工程 · Sepolia 运行时已对齐 — 广播未开始',
    'Mainnet release engineering · Sepolia runtime aligned — broadcast not started',
    'Phase 2.5 加固已 CLOSED。运行时证据与主网规划输入已冻结 — 非主网广播承诺。',
    'Phase 2.5 hardening is CLOSED. Runtime evidence and mainnet planning inputs are frozen — not a mainnet broadcast commitment.',
    '2026-07-09',
    'learn_more',
    '/governance/params',
    'testnet',
    'traveltrust_pulse_phase3_entry',
    now()
),
(
    'product-deploy-phase3',
    'protocol_status',
    'product',
    'live',
    'published',
    false,
    80,
    'Phase 3 · Sepolia ACTIVE — 区域经济',
    'Phase 3 · Sepolia ACTIVE — regional economy',
    '区域经济与主理人能力已在 Sepolia ACTIVE — 非主网生产。',
    'Regional economy and steward capabilities are Sepolia ACTIVE — not mainnet production.',
    '2026-07-09',
    'learn_more',
    '/governance/params',
    'testnet',
    'traveltrust_pulse_deploy_phase3',
    now()
),
(
    'product-deploy-phase2',
    'protocol_status',
    'product',
    'live',
    'published',
    false,
    60,
    'Phase 2 · Sepolia ACTIVE — 治理与身份',
    'Phase 2 · Sepolia ACTIVE — governance and identity',
    '治理提案与身份质押已在 Sepolia ACTIVE — 仅测试网。',
    'Governance proposals and identity stake are Sepolia ACTIVE — testnet only.',
    '2026-07-09',
    'learn_more',
    '/governance/proposals',
    'testnet',
    'traveltrust_pulse_deploy_phase2',
    now()
),
(
    'product-deploy-phase1',
    'protocol_status',
    'product',
    'live',
    'published',
    false,
    40,
    'Phase 1 · Sepolia ACTIVE — Web3 核心 · 托管 · TTG · 治理',
    'Phase 1 · Sepolia ACTIVE — Web3 core · escrow · TTG · governance',
    'Sepolia 测试网已 ACTIVE：托管、TTG 认购与治理参数只读查阅。',
    'Sepolia testnet ACTIVE: escrow, TTG subscription, and read-only governance params.',
    '2026-07-09',
    'learn_more',
    '/traveltrust#liquidity',
    'testnet',
    'traveltrust_pulse_deploy_phase1',
    now()
)
ON CONFLICT (slug) DO UPDATE SET
    lane = EXCLUDED.lane,
    kind = EXCLUDED.kind,
    content_tier = EXCLUDED.content_tier,
    publish_status = 'published',
    pinned = EXCLUDED.pinned,
    sort_order = EXCLUDED.sort_order,
    title_zh = EXCLUDED.title_zh,
    title_en = EXCLUDED.title_en,
    summary_zh = EXCLUDED.summary_zh,
    summary_en = EXCLUDED.summary_en,
    effective_at = EXCLUDED.effective_at,
    cta_kind = EXCLUDED.cta_kind,
    cta_href = EXCLUDED.cta_href,
    network_scope = EXCLUDED.network_scope,
    message_key = EXCLUDED.message_key,
    published_at = COALESCE(cms_public_announcements.published_at, now()),
    version = cms_public_announcements.version + 1,
    updated_at = now();
