#!/usr/bin/env bash
# Bootstrap scripts/dev/.env.production.local + deploy/fly/tt-web-prod/build.env.local
# from staging SSOT (Sepolia scope) · new prod-only secrets · SEED=0
#
#   PROD_WEB_BASE=https://app.example.com PROD_API_BASE=https://api.example.com \
#     bash scripts/dev/bootstrap-prod-env-from-staging.sh
#
# Default (interim): tt-web-prod.fly.dev / tt-api-prod.fly.dev — NOT sufficient for final GO audit P3-PROD-DOMAIN
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STAGING_ENV="${STAGING_SECRETS_FILE:-$ROOT/scripts/dev/.env.staging-secrets.local}"
STAGING_BUILD_ENV="${STAGING_BUILD_ENV:-$ROOT/deploy/fly/tt-web-staging/build.env.local}"
PROD_ENV="$ROOT/scripts/dev/.env.production.local"
BUILD_ENV="$ROOT/deploy/fly/tt-web-prod/build.env.local"
BUILD_EXAMPLE="$ROOT/deploy/fly/tt-web-prod/build.env.sepolia-prod.example"

PROD_WEB_BASE="${PROD_WEB_BASE:-https://tt-web-prod.fly.dev}"
PROD_API_BASE="${PROD_API_BASE:-https://tt-api-prod.fly.dev}"
PROD_WEB_BASE="${PROD_WEB_BASE%/}"
PROD_API_BASE="${PROD_API_BASE%/}"

fail() { echo "bootstrap-prod-env: FAIL $*" >&2; exit 2; }
ok() { echo "bootstrap-prod-env: OK $*"; }

[[ -f "$STAGING_ENV" ]] || fail "missing staging secrets $STAGING_ENV"

merge_env() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%%#*}"
    line="$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    [[ -z "$line" || "$line" != *=* ]] && continue
    key="${line%%=*}"
    val="${line#*=}"
    val="${val%\"}"; val="${val#\"}"
    val="${val%\'}"; val="${val#\'}"
    export "$key=$val"
  done <"$f"
}

merge_env "$STAGING_ENV"
merge_env "$STAGING_BUILD_ENV"

EXISTING_INTERNAL=""
EXISTING_DATABASE=""
if [[ -f "$PROD_ENV" ]]; then
  EXISTING_INTERNAL="$(grep -E '^INTERNAL_API_SECRET=' "$PROD_ENV" | head -1 | cut -d= -f2- || true)"
  EXISTING_DATABASE="$(grep -E '^DATABASE_URL=' "$PROD_ENV" | head -1 | cut -d= -f2- || true)"
fi
if [[ -z "${EXISTING_DATABASE:-}" ]] && command -v fly >/dev/null 2>&1; then
  if fly secrets list -a "${FLY_PROD_API_APP:-tt-api-prod}" 2>/dev/null | grep -q '^DATABASE_URL[[:space:]]'; then
    if fly status -a "${FLY_PROD_API_APP:-tt-api-prod}" 2>/dev/null | grep -q 'STATE.*started'; then
      EXISTING_DATABASE="$(fly ssh console -a "${FLY_PROD_API_APP:-tt-api-prod}" -C 'printenv DATABASE_URL' 2>/dev/null | tr -d '\r' | head -1 || true)"
    fi
  fi
fi

NEW_INTERNAL="$(openssl rand -hex 32 2>/dev/null || python -c 'import secrets; print(secrets.token_hex(32))')"
[[ -n "${EXISTING_INTERNAL:-}" ]] && NEW_INTERNAL="$EXISTING_INTERNAL"
# Prod DATABASE_URL must come from tt-traveltrust-prod attach — never copy staging URL
unset DATABASE_URL
[[ -n "${EXISTING_DATABASE:-}" ]] && export DATABASE_URL="$EXISTING_DATABASE"

# Chain SSOT from staging build env when staging secrets omit contract addresses
[[ -n "${NEXT_PUBLIC_CHAIN_ID:-}" && -z "${CHAIN_ID:-}" ]] && CHAIN_ID="$NEXT_PUBLIC_CHAIN_ID"
[[ -n "${NEXT_PUBLIC_RPC_URL:-}" && -z "${CHAIN_RPC_URL:-}" ]] && CHAIN_RPC_URL="$NEXT_PUBLIC_RPC_URL"
[[ -n "${NEXT_PUBLIC_ESCROW_FACTORY_ADDRESS:-}" && -z "${ESCROW_FACTORY_ADDRESS:-}" ]] && ESCROW_FACTORY_ADDRESS="$NEXT_PUBLIC_ESCROW_FACTORY_ADDRESS"
[[ -n "${NEXT_PUBLIC_FEE_ROUTER_ADDRESS:-}" && -z "${FEE_ROUTER_ADDRESS:-}" ]] && FEE_ROUTER_ADDRESS="$NEXT_PUBLIC_FEE_ROUTER_ADDRESS"
[[ -n "${NEXT_PUBLIC_GOVERNOR_ADDRESS:-}" && -z "${GOVERNOR_ADDRESS:-}" ]] && GOVERNOR_ADDRESS="$NEXT_PUBLIC_GOVERNOR_ADDRESS"
[[ -n "${NEXT_PUBLIC_REGISTRY_ADDRESS:-}" && -z "${REGISTRY_ADDRESS:-}" ]] && REGISTRY_ADDRESS="$NEXT_PUBLIC_REGISTRY_ADDRESS"
[[ -n "${NEXT_PUBLIC_GUIDE_STAKING_ADDRESS:-}" && -z "${GUIDE_STAKING_POOL_ADDRESS:-}" ]] && GUIDE_STAKING_POOL_ADDRESS="$NEXT_PUBLIC_GUIDE_STAKING_ADDRESS"
[[ -n "${NEXT_PUBLIC_STAKING_PROVIDER_ADDRESS:-}" && -z "${PROVIDER_STAKING_POOL_ADDRESS:-}" ]] && PROVIDER_STAKING_POOL_ADDRESS="$NEXT_PUBLIC_STAKING_PROVIDER_ADDRESS"

SSOT_DOC="$ROOT/docs/spec/08-3-参数与门禁表.md"
if [[ -f "$SSOT_DOC" ]]; then
  if command -v sha256sum >/dev/null 2>&1; then
    SSOT_SHA256="$(sha256sum "$SSOT_DOC" | awk '{print $1}')"
  elif command -v shasum >/dev/null 2>&1; then
    SSOT_SHA256="$(shasum -a 256 "$SSOT_DOC" | awk '{print $1}')"
  fi
fi
SSOT_VERSION="${SSOT_VERSION:-1.0.0}"
CHARGEBACK_POLICY="${CHARGEBACK_POLICY:-warn}"

mkdir -p "$(dirname "$BUILD_ENV")"
cat >"$PROD_ENV" <<EOF
# Generated by bootstrap-prod-env-from-staging.sh · $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Owner: review before Production GO · do not commit

SEED_TEST_ACCOUNTS=0
P3_CHAIN_OFF=

PROD_WEB_BASE=${PROD_WEB_BASE}
PROD_API_BASE=${PROD_API_BASE}
PUBLIC_API_BASE_URL=${PROD_API_BASE}
CORS_ORIGINS=${PROD_WEB_BASE}

DATABASE_URL=${DATABASE_URL:-}
INTERNAL_API_SECRET=${NEW_INTERNAL}

CHAIN_ID=${CHAIN_ID:-11155111}
CHAIN_RPC_URL=${CHAIN_RPC_URL:-}
ESCROW_FACTORY_ADDRESS=${ESCROW_FACTORY_ADDRESS:-}
FEE_ROUTER_ADDRESS=${FEE_ROUTER_ADDRESS:-}
REGION_VAULT_ADDRESS=${REGION_VAULT_ADDRESS:-}
REGISTRY_ADDRESS=${REGISTRY_ADDRESS:-}
GOVERNOR_ADDRESS=${GOVERNOR_ADDRESS:-}
GOVERNANCE_TOKEN_ADDRESS=${GOVERNANCE_TOKEN_ADDRESS:-}
GUIDE_STAKING_POOL_ADDRESS=${GUIDE_STAKING_POOL_ADDRESS:-}
PROVIDER_STAKING_POOL_ADDRESS=${PROVIDER_STAKING_POOL_ADDRESS:-}

# PI3-003: replace with sk_live_* / live whsec_* before PI3-003 GO
TRAVELTRUST_ONBOARDING_STRIPE_ENABLED=${TRAVELTRUST_ONBOARDING_STRIPE_ENABLED:-0}
TRAVELTRUST_STRIPE_SECRET_KEY=
TRAVELTRUST_STRIPE_WEBHOOK_SECRET=

STRICT_SSOT=${STRICT_SSOT:-1}
STRICT_SESSION_GATE=${STRICT_SESSION_GATE:-1}
REQUIRE_IDempotency_KEY=${REQUIRE_IDEMPOTENCY_KEY:-1}
SSOT_VERSION=${SSOT_VERSION}
SSOT_SHA256=${SSOT_SHA256:-}
CHARGEBACK_POLICY=${CHARGEBACK_POLICY}

FLY_PROD_API_APP=tt-api-prod
FLY_PROD_WEB_APP=tt-web-prod
FLY_PROD_PG_APP=tt-traveltrust-prod
EOF

# Fix typo REQUIRE_IDEMPOTENCY_KEY
sed -i 's/REQUIRE_IDempotency_KEY/REQUIRE_IDEMPOTENCY_KEY/' "$PROD_ENV" 2>/dev/null || \
  sed -i '' 's/REQUIRE_IDempotency_KEY/REQUIRE_IDEMPOTENCY_KEY/' "$PROD_ENV" 2>/dev/null || true

cp "$BUILD_EXAMPLE" "$BUILD_ENV"
sed -i "s|https://api.example.com|${PROD_API_BASE}|g" "$BUILD_ENV" 2>/dev/null || \
  sed -i '' "s|https://api.example.com|${PROD_API_BASE}|g" "$BUILD_ENV"
sed -i "s|https://app.example.com|${PROD_WEB_BASE}|g" "$BUILD_ENV" 2>/dev/null || \
  sed -i '' "s|https://app.example.com|${PROD_WEB_BASE}|g" "$BUILD_ENV"

# Contract addresses from staging into build env if set
for pair in \
  ESCROW_FACTORY_ADDRESS:NEXT_PUBLIC_ESCROW_FACTORY_ADDRESS \
  FEE_ROUTER_ADDRESS:NEXT_PUBLIC_FEE_ROUTER_ADDRESS \
  GOVERNOR_ADDRESS:NEXT_PUBLIC_GOVERNOR_ADDRESS \
  REGISTRY_ADDRESS:NEXT_PUBLIC_REGISTRY_ADDRESS \
  GUIDE_STAKING_POOL_ADDRESS:NEXT_PUBLIC_GUIDE_STAKING_ADDRESS \
  PROVIDER_STAKING_POOL_ADDRESS:NEXT_PUBLIC_STAKING_PROVIDER_ADDRESS; do
  src="${pair%%:*}"; dst="${pair#*:}"
  val="${!src:-}"
  [[ -n "$val" ]] && sed -i "s|^${dst}=.*|${dst}=${val}|" "$BUILD_ENV" 2>/dev/null || \
    sed -i '' "s|^${dst}=.*|${dst}=${val}|" "$BUILD_ENV" 2>/dev/null || true
done

ok "wrote $PROD_ENV"
ok "wrote $BUILD_ENV"
echo "PROD_WEB_BASE=${PROD_WEB_BASE}"
echo "PROD_API_BASE=${PROD_API_BASE}"
if [[ "$PROD_WEB_BASE" == *fly.dev* ]]; then
  echo "WARN: *.fly.dev interim — P3-PROD-DOMAIN stays BLOCKER until brand domain (PI3-002 Owner §A)"
fi
[[ -n "${DATABASE_URL:-}" ]] || echo "WARN: DATABASE_URL empty — set after fly postgres attach tt-traveltrust-prod"
