#!/usr/bin/env bash
# Phase ① · Anvil · EscrowFactoryV2 (bilateral settlement path)
#
#   bash scripts/dev/deploy-escrow-factory-v2-anvil-local.sh
#   bash scripts/dev/deploy-escrow-factory-v2-anvil-local.sh --apply
#
# Prerequisite: anvil running (or deploy-fundstack-anvil-local.sh first for full stack)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# shellcheck source=scripts/dev/lib/fundstack-anvil-common.sh
source "$ROOT/scripts/dev/lib/fundstack-anvil-common.sh"
# shellcheck source=scripts/dev/lib/web3-phase-boundary.sh
source "$ROOT/scripts/dev/lib/web3-phase-boundary.sh"

APPLY=0
for arg in "$@"; do
  [[ "$arg" == "--apply" ]] && APPLY=1
done

fundstack_anvil_ensure_anvil
fundstack_anvil_ensure_tools

RPC="$FUNDSTACK_ANVIL_RPC"
PK="${FUNDSTACK_ANVIL_DEPLOYER_PK:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}"
CHAIN_ID="$(cast chain-id --rpc-url "$RPC")"
web3_assert_phase12_chain "$CHAIN_ID" "DeployEscrowFactoryV2Anvil"

ENV_OUT="$ROOT/scripts/dev/.env.escrow-v2-anvil.local"
LOG="$(mktemp)"

cd "$ROOT/contracts"
DEPLOY_OUT="$(PRIVATE_KEY="$PK" forge script script/DeployEscrowFactoryV2Anvil.s.sol:DeployEscrowFactoryV2Anvil \
  --rpc-url "$RPC" --broadcast 2>&1 | tee "$LOG")" || fundstack_anvil_fail "DeployEscrowFactoryV2Anvil failed"

grep -q "ESCROW_FACTORY_V2_ANVIL_BINDING_CHECK: OK" "$LOG" || fundstack_anvil_fail "missing binding check in deploy log"

FACTORY_V2="$(echo "$DEPLOY_OUT" | grep -F "EscrowFactoryV2" | grep -oE '0x[a-fA-F0-9]{40}' | tail -1)"
[[ -n "$FACTORY_V2" ]] || fundstack_anvil_fail "parse EscrowFactoryV2 address failed"

cat >"$ENV_OUT" <<EOF
# Generated by deploy-escrow-factory-v2-anvil-local.sh — Phase ① Anvil EscrowV2
CHAIN_RPC_URL=$RPC
CHAIN_ID=$CHAIN_ID
ESCROW_FACTORY_V2_ADDRESS=$FACTORY_V2
NEXT_PUBLIC_ESCROW_FACTORY_V2_ADDRESS=$FACTORY_V2
WEB3_PHASE=1
EOF

fundstack_anvil_ok "EscrowFactoryV2=$FACTORY_V2"
fundstack_anvil_ok "wrote $ENV_OUT"

if [[ "$APPLY" == "1" ]]; then
  block_begin="# --- BEGIN TT ESCROW V2 ANVIL (deploy-escrow-factory-v2-anvil-local.sh) ---"
  block_end="# --- END TT ESCROW V2 ANVIL ---"
  root_env="$ROOT/.env"
  tmp="$(mktemp)"
  if [[ -f "$root_env" ]] && grep -qF "$block_begin" "$root_env"; then
    awk -v b="$block_begin" -v e="$block_end" '
      $0 == b { skip=1; next }
      $0 == e { skip=0; next }
      !skip { print }
    ' "$root_env" >"$tmp"
    mv "$tmp" "$root_env"
  fi
  {
    echo "$block_begin"
    cat "$ENV_OUT"
    echo "$block_end"
  } >>"$root_env"
  fundstack_anvil_ok "merged into $root_env"
fi

echo "TT_ESCROW_FACTORY_V2_ANVIL_DEPLOY: OK"
