#!/usr/bin/env bash
# Admin ① L5 绿集：首页 · Shell · 顶栏管理员入口（非 ②③ GO）
# Windows 无 bash 时：node scripts/dev/run-admin-l5-green.mjs
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT/frontend"
npx vitest run \
  lib/admin/adminHomeKpiMetric.test.ts \
  lib/admin/adminHomeInboxPendingTotal.test.ts \
  lib/admin/adminHomeFocusModuleFilter.test.ts \
  lib/admin/adminSectionBackLinksL5.contract.test.ts \
  lib/admin/adminPageHeaderBackLinksL5.contract.test.ts \
  lib/admin/adminShellUxPolicy.test.ts \
  lib/admin/adminInboxChannelPermission.test.ts \
  lib/admin/adminShellContextForPath.test.ts \
  lib/admin/adminListPageWritePermission.test.ts \
  lib/admin/adminTableA11y.contract.test.ts \
  lib/admin/adminVisL5.contract.test.ts \
  lib/admin/adminPageChromeL5.contract.test.ts \
  lib/admin/adminHonestyL5.contract.test.ts \
  lib/admin/adminContrastL5.contract.test.ts \
  lib/admin/adminConfigPublishL5.contract.test.ts \
  lib/admin/adminComplianceDsarL5.contract.test.ts \
  lib/admin/adminQueueFocusL5.contract.test.ts \
  lib/admin/adminModalA11yL5.contract.test.ts \
  lib/admin/adminLoadingL5.contract.test.ts \
  lib/admin/adminErrorBoundaryL5.contract.test.ts \
  lib/admin/adminFilterChipL5.contract.test.ts \
  lib/admin/adminSuccessWizardL5.contract.test.ts \
  lib/admin/adminActorFromMe.test.ts \
  lib/admin/adminHomeVisibility.test.ts \
  lib/admin/adminHomeCardCapability.test.ts \
  lib/admin/useAdminCapabilities.test.ts \
  lib/admin/useAdminHomeQueues.test.ts \
  lib/admin/adminRole70Matrix.test.ts \
  lib/admin/adminHomeCardPermission.test.ts \
  lib/admin/adminRoutePermission.test.ts \
  lib/admin/adminAllRoutesPermission.contract.test.ts \
  lib/admin/admU01StagingShellMatrix.contract.test.ts \
  lib/admin/adminConsoleRolePreviewL5.contract.test.ts \
  lib/admin/adminPhase1BacklogClosureL5.contract.test.ts \
  lib/admin/adminPhase2RemainingBacklogL5.contract.test.ts \
  lib/admin/adminFinancePartialDepthL5.contract.test.ts \
  lib/admin/adminFinanceSuiteBackLinksL5.contract.test.ts \
  lib/admin/adminRemainingSixL5.contract.test.ts \
  lib/admin/adminPhase1DataHonesty.contract.test.ts \
  lib/admin/adminL5ConfirmL5.contract.test.ts \
  lib/admin/adminAuditLogWriteL5.contract.test.ts \
  lib/admin/adminNavPerfL5.contract.test.ts \
  lib/admin/adminBatchADataFreshnessL5.contract.test.ts \
  lib/admin/adminAuthSessionReset.test.ts \
  lib/admin/adminHomeInboxQueueListCache.test.ts \
  lib/admin/adminPostWriteCacheInvalidation.test.ts \
  lib/admin/adminListFetchCache.test.ts \
  lib/admin/adminNavBootReady.test.ts \
  lib/admin/adminSessionExpiredClient.test.ts \
  lib/admin/adminRoutePrefetchSession.test.ts \
  lib/admin/adminLocaleParityL5.contract.test.ts \
  lib/admin/adminPhase1FullClosureL5.contract.test.ts \
  lib/admin/adminListStaleWhileErrorL5.contract.test.ts \
  lib/admin/adminHomeSectionPending.test.ts \
  lib/admin/adminCapabilitiesFetchCache.test.ts \
  lib/admin/adminShellPrefetchHref.test.ts \
  lib/admin/adminFinanceReconciliationBundleFetch.test.ts \
  lib/admin/adminHomeOverviewFetchCache.test.ts \
  lib/admin/adminHomeSystemOverviewMetrics.test.ts \
  lib/admin/adminShellNavGroupsL5.contract.test.ts \
  lib/admin/adminRoutePrefetchL5.contract.test.ts \
  lib/admin/adminShellOnboardingNavL5.contract.test.ts \
  lib/admin/adminUnifiedInboxTasks.test.ts \
  lib/admin/adminInboxWorkflowOrder.test.ts \
  lib/admin/adminInboxQueuePath.test.ts \
  lib/admin/adminInboxQueueBackLinksL5.contract.test.ts \
  lib/admin/adminInboxQueueNavAlignment.contract.test.ts \
  lib/admin/adminShellSidebarL5.contract.test.ts \
  lib/admin/adminBatch2UxL5.contract.test.ts \
  lib/admin/adminBatch3UxL5.contract.test.ts \
  lib/admin/adminBatch4UxL5.contract.test.ts \
  lib/admin/adminBatch5UxL5.contract.test.ts \
  lib/admin/adminBatch6UxL5.contract.test.ts \
  lib/admin/adminBatch7UxL5.contract.test.ts \
  lib/admin/adminBatch8UxL5.contract.test.ts \
  lib/admin/adminBatch9UxL5.contract.test.ts \
  lib/admin/adminBatch10UxL5.contract.test.ts \
  lib/admin/adminBatch11UxL5.contract.test.ts \
  lib/admin/adminBatch12UxL5.contract.test.ts \
  lib/admin/adminBatch13UxL5.contract.test.ts \
  lib/admin/adminBatch14UxL5.contract.test.ts \
  lib/admin/adminBatch15UxL5.contract.test.ts \
  lib/admin/adminBatch16UxL5.contract.test.ts \
  lib/admin/adminBatch17UxL5.contract.test.ts \
  lib/admin/adminBatch18UxL5.contract.test.ts \
  lib/admin/adminBatch19UxL5.contract.test.ts \
  lib/admin/adminBatch20UxL5.contract.test.ts \
  lib/admin/adminBatch21UxL5.contract.test.ts \
  lib/admin/adminBatch22UxL5.contract.test.ts \
  lib/admin/adminBatch23UxL5.contract.test.ts \
  lib/admin/adminBatch24UxL5.contract.test.ts \
  lib/admin/adminBatch25UxL5.contract.test.ts \
  lib/admin/adminBatch26UxL5.contract.test.ts \
  lib/admin/adminBatch27UxL5.contract.test.ts \
  lib/admin/adminBatch28UxL5.contract.test.ts \
  lib/admin/adminBatch29UxL5.contract.test.ts \
  lib/admin/adminBatch30UxL5.contract.test.ts \
  lib/admin/adminBatch31UxL5.contract.test.ts \
  lib/admin/adminBatch32UxL5.contract.test.ts \
  lib/admin/adminBatch33UxL5.contract.test.ts \
  lib/admin/adminBatch34UxL5.contract.test.ts \
  lib/admin/adminBatch35UxL5.contract.test.ts \
  lib/admin/adminBatch36UxL5.contract.test.ts \
  lib/admin/adminPlatformHubL5.contract.test.ts \
  lib/admin/adminBatch37UxL5.contract.test.ts \
  lib/admin/adminBatch38UxL5.contract.test.ts \
  lib/admin/adminBatch39UxL5.contract.test.ts \
  lib/admin/adminBatch40UxL5.contract.test.ts \
  lib/admin/adminBatch41UxL5.contract.test.ts \
  lib/admin/adminBatch42UxL5.contract.test.ts \
  lib/admin/adminBatch43UxL5.contract.test.ts \
  lib/admin/adminBatch44UxL5.contract.test.ts \
  lib/admin/adminBatch45UxL5.contract.test.ts \
  lib/admin/adminBatch46UxL5.contract.test.ts \
  lib/admin/adminBatch47UxL5.contract.test.ts \
  lib/admin/adminBatch48UxL5.contract.test.ts \
  lib/admin/adminBatch49UxL5.contract.test.ts \
  lib/admin/adminBatch50UxL5.contract.test.ts \
  lib/admin/adminBatch51UxL5.contract.test.ts \
  lib/admin/adminBatch52UxL5.contract.test.ts \
  lib/admin/adminBatch53UxL5.contract.test.ts \
  lib/admin/adminBatch54UxL5.contract.test.ts \
  lib/admin/adminBatch55UxL5.contract.test.ts \
  lib/admin/adminBatch56UxL5.contract.test.ts \
  lib/admin/adminBatch57UxL5.contract.test.ts \
  lib/admin/adminBatch58UxL5.contract.test.ts \
  lib/admin/adminBatch59UxL5.contract.test.ts \
  lib/admin/adminBatch60UxL5.contract.test.ts \
  lib/admin/adminPhase29W2.contract.test.ts \
  lib/admin/adminP1UxFixes.contract.test.ts \
  lib/admin/adminConsoleRole70PickOrder.test.ts \
  lib/admin/adminCapabilityStripVisibility.test.ts \
  lib/admin/adminShellPendingBadgePolicy.test.ts \
  lib/admin/adminPhase2RemainingBacklogPrepHref.test.ts \
  lib/admin/adminLocalePhase2UxKeysL5.contract.test.ts \
  lib/admin/adminPhase2LocalPrepCommands.test.ts \
  lib/admin/adminReportsModerationWizardValidation.test.ts \
  lib/admin/adminFinanceWorkflowNextStep.test.ts \
  lib/admin/adminFinanceDepthPanelsL5.contract.test.ts \
  lib/admin/adminFinancePartialDepthHref.test.ts \
  lib/admin/adminShellInboxNavBadge.test.ts \
  lib/admin/adminShellNavParityL5.contract.test.ts \
  lib/admin/adminShellMoreNavLinks.test.ts \
  lib/admin/adminPlatformHubHeaderNav.test.ts \
  lib/admin/adminHomeInboxQueueCardsL5.contract.test.ts \
  lib/admin/adminRecentVisits.test.ts \
  lib/admin/adminRecentVisitsL5.contract.test.ts \
  lib/admin/adminCommandPaletteL5.contract.test.ts \
  lib/admin/adminStyleAlignmentL5.contract.test.ts \
  lib/admin/adminWarmL5CoverageL5.contract.test.ts \
  lib/admin/adminListEmptyStateNextLinksL5.contract.test.ts \
  lib/admin/adminQueueStatusL5.contract.test.ts \
  lib/admin/adminAttentionL5.contract.test.ts \
  lib/admin/adminShellCommunityNav.contract.test.ts \
  lib/admin/adminHomeDomainHealth.test.ts \
  lib/admin/useAdminTableSort.test.ts \
  lib/admin/adminThemeL5.contract.test.ts \
  lib/admin/adminMotionL5.contract.test.ts \
  lib/admin/sortOnboardingQueueItems.test.ts \
  app/admin/inbox/adminUnifiedInboxL5.contract.test.ts \
  components/admin/adminOnboardingListPage.contract.test.ts \
  app/admin/community/reports/adminCommunityReportsPage.contract.test.ts \
  app/admin/community/abuse-policy/adminCommunityAbusePolicyPage.contract.test.ts \
  app/admin/community/appeals/review/adminCommunityAppealReviewPage.contract.test.ts \
  app/admin/community/comments/visibility/adminCommunityCommentVisibilityPage.contract.test.ts \
  app/admin/community/appeals/adminCommunityAppealsPage.contract.test.ts \
  components/admin/adminShellBarL5.contract.test.ts \
  components/admin/adminHomeL5.contract.test.ts \
  components/admin/adminHomePrimaryCtasL5.contract.test.ts \
  components/admin/adminLayoutSubpageNavL5.contract.test.ts \
  components/header/headerUserMenuAdminNav.contract.test.ts \
  components/header/headerAdminModeL5.contract.test.ts \
  app/admin/provider-applications/adminProviderApplicationsPage.contract.test.ts \
  app/admin/steward-applications/adminStewardApplicationsPage.contract.test.ts \
  app/admin/permissions/adminPermissionsDbPrep.contract.test.ts \
  app/admin/permissions/adminPermissionsPage.contract.test.ts \
  app/admin/onboarding/entitlements/adminOnboardingEntitlementsPage.contract.test.ts \
  app/admin/onboarding/webhook-jobs/adminOnboardingWebhookJobsPage.contract.test.ts \
  app/admin/onboarding/payment-events/adminOnboardingPaymentEventsPage.contract.test.ts \
  app/admin/onboarding/compliance-audit/adminOnboardingComplianceAuditPage.contract.test.ts \
  app/admin/users/adminUsersPage.contract.test.ts \
  app/admin/community/penalties/adminCommunityPenaltiesPage.contract.test.ts \
  app/admin/community/moderation/cases/adminCommunityModerationCasesPage.contract.test.ts \
  app/admin/community/risk-signals/adminCommunityRiskSignalsPage.contract.test.ts \
  app/admin/community/policy-change-logs/adminCommunityPolicyChangeLogsPage.contract.test.ts \
  app/admin/community/ranking/snapshots/adminCommunityRankingSnapshotsPage.contract.test.ts \
  app/admin/adminMissingPages.contract.test.ts \
  app/admin/finance-suite/adminFinanceSuitePage.contract.test.ts \
  app/admin/finance-suite/adminFinanceSuiteL5.contract.test.ts \
  app/admin/finance/adminFinancePage.contract.test.ts \
  'app/admin/onboarding/entitlements/[id]/adminOnboardingEntitlementDetailPage.contract.test.ts' \
  app/admin/provider-applications/adminProviderApplicationsPage.contract.test.ts \
  app/admin/adminUxShared.contract.test.ts \
  app/admin/adminPrimaryAction.contract.test.ts \
  app/admin/guides/adminGuidesPage.contract.test.ts \
  app/admin/audit/adminAuditPage.contract.test.ts \
  app/admin/auth-audit-events/adminAuthAuditEventsL5.contract.test.ts \
  app/admin/flags/adminFlagsPage.contract.test.ts \
  app/admin/policies/adminPoliciesPage.contract.test.ts \
  app/admin/compliance/adminComplianceHubPage.contract.test.ts \
  app/admin/onboarding/adminOnboardingHubPage.contract.test.ts \
  app/admin/onboarding/adminOnboardingHubL5.contract.test.ts \
  app/admin/operator-guide/adminOperatorGuidePage.contract.test.ts \
  app/admin/approvals/adminApprovalsPage.contract.test.ts \
  'app/admin/approvals/[id]/adminApprovalDetailPage.contract.test.ts' \
  app/admin/orders/adminOrdersPage.contract.test.ts \
  app/admin/disputes/adminDisputesPage.contract.test.ts \
  app/admin/jobs/adminJobsPage.contract.test.ts \
  app/admin/lifecycle/adminLifecyclePage.contract.test.ts \
  app/admin/api-versions/adminApiVersionsPage.contract.test.ts \
  app/admin/scheduler/jobs/adminSchedulerJobsPage.contract.test.ts \
  app/admin/internal-tools/audits/adminInternalToolAuditsPage.contract.test.ts \
  app/admin/secrets/metadata/adminSecretsMetadataPage.contract.test.ts \
  app/admin/tenants/scopes/adminTenantScopesPage.contract.test.ts \
  app/admin/config/releases/adminConfigReleasesPage.contract.test.ts \
  app/admin/media/signed-url-tokens/adminMediaSignedUrlTokensPage.contract.test.ts \
  app/admin/media/access-logs/adminMediaAccessLogsPage.contract.test.ts \
  app/admin/audit/operations/adminAuditOperationsPage.contract.test.ts \
  app/admin/reviews/adminReviewsPage.contract.test.ts \
  app/admin/alerts/incidents/adminAlertIncidentsHubPage.contract.test.ts \
  app/admin/indexer/reconcile-reports/adminIndexerReconcileReportsPage.contract.test.ts \
  app/admin/region-vault/adminRegionVaultPage.contract.test.ts \
  app/admin/fee-router/adminFeeRouterPage.contract.test.ts \
  app/admin/indexer/adminIndexerPage.contract.test.ts \
  app/admin/observability/adminObservabilityPage.contract.test.ts \
  app/admin/schema/adminSchemaPage.contract.test.ts \
  app/admin/config/adminConfigHubPage.contract.test.ts \
  app/admin/trust-growth/adminTrustGrowthPage.contract.test.ts \
  app/admin/finance-reconciliation/adminFinanceReconciliationPage.contract.test.ts \
  app/admin/cross-check/adminCrossCheckPage.contract.test.ts \
  app/admin/cross-check/page.test.tsx \
  app/admin/drift-summary/adminDriftSummaryPage.contract.test.ts \
  'app/admin/alerts/incidents/[id]/adminAlertIncidentDetailPage.contract.test.ts' \
  'app/admin/users/[id]/adminUserDetailPage.contract.test.ts' \
  'app/admin/orders/[id]/adminOrderDetailPage.contract.test.ts' \
  'app/admin/disputes/[id]/adminDisputeDetailPage.contract.test.ts' \
  'app/admin/guides/[id]/adminGuideDetailPage.contract.test.ts' \
  'app/admin/audit/logs/[id]/adminAuditLogDetailPage.contract.test.ts' \
  'app/admin/config/releases/[id]/adminConfigReleaseDetailPage.contract.test.ts' \
  'app/admin/indexer/reconcile/[id]/adminIndexerReconcileReportPage.contract.test.ts' \
  'app/admin/compliance/requests/[requestId]/update/adminComplianceRequestUpdatePage.contract.test.ts' \
  'app/admin/reviews/[id]/adminReviewDetailPage.contract.test.ts' \
  'app/admin/compliance/requests/[requestId]/events/adminComplianceRequestEventsPage.contract.test.ts' \
  components/admin/adminRoutePermissionBanner.contract.test.ts \
  lib/admin/adminOpsPlaneUxL5.contract.test.ts \
  app/admin/content/adminContentCs1.contract.test.ts \
  app/admin/content/adminContentCs2.contract.test.ts \
  app/admin/content/adminContentCs3.contract.test.ts \
  app/admin/content/adminContentCs4.contract.test.ts \
  app/admin/content/adminContentCs5.contract.test.ts \
  app/admin/content/adminContentCs6.contract.test.ts \
  app/admin/official/adminOfficialOs1.contract.test.ts \
  app/admin/official/adminOfficialOs2.contract.test.ts \
  app/admin/official/adminOfficialOs3.contract.test.ts \
  app/admin/official/adminOfficialOs4.contract.test.ts \
  app/admin/growth/referral-codes/adminGrowthReferralCodes.contract.test.ts \
  app/admin/growth/early-bird/adminGrowthEarlyBird.contract.test.ts \
  app/admin/growth/reward-ledger/adminGrowthRewardLedger.contract.test.ts \
  app/admin/growth/anti-fraud/adminGrowthAntiFraud.contract.test.ts \
  app/admin/growth/airdrop-campaigns/adminGrowthAirdrop.contract.test.ts \
  app/admin/growth/analytics/adminGrowthAnalytics.contract.test.ts \
  app/admin/growth/kol-center/adminGrowthKolCenter.contract.test.ts \
  app/me/referrals/meReferralsPage.contract.test.ts \
  lib/coldStartCampaign/coldStartCampaignE2eA01.contract.test.ts \
  --run
echo "admin-l5-green: exit 0"
