#!/usr/bin/env python3
"""Write M5-M9 depth residual pack (REGISTER_ONLY)."""
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] if False else Path(".")
CAP = Path("evidence/GO_official_product_reality_capture")


def main() -> None:
    m5 = json.loads((CAP / "M5_ENV_FLAGS_SCAN_20260822.json").read_text(encoding="utf-8"))
    m6 = json.loads((CAP / "M6_API_META_COMPARE_20260822.json").read_text(encoding="utf-8"))
    mig_n = m6.get("local_sql_migrationish_count")
    items = [
        {
            "id": "M5-01",
            "module": "M5",
            "class": "RESIDUAL",
            "surface": "Local frontend/.env.local SKIP_ME_FETCH",
            "observed": "needle present in local env",
            "required_official": "Official bootstrap v8 SKIP_ME_FETCH=0",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M5-02",
            "module": "M5",
            "class": "CONFIRM_DESIGN",
            "surface": "ESCROW_DEV_TOOLS / MARKET_DEV_VARIETY docs",
            "observed": "Local/dev-only in freezes",
            "required_official": "must not enable on Official/Staging product bake",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M5-03",
            "module": "M5",
            "class": "RESIDUAL",
            "surface": "Local Runtime vs Official image",
            "observed": "Capture Config OPEN",
            "required_official": "Fly secrets/runtime inventory vs pin",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M6-01",
            "module": "M6",
            "class": "ED",
            "surface": "API build.git_sha",
            "observed": "8df2ab21 vs 1915ec4d",
            "required_official": "Official API pin 8df2ab21",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M6-02",
            "module": "M6",
            "class": "ED",
            "surface": "API chain.chain_id",
            "observed": "1 vs 11155111",
            "required_official": "Official mainnet API",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M6-03",
            "module": "M6",
            "class": "CONFIRM_DESIGN",
            "surface": "API service/api_version",
            "observed": "SAME",
            "required_official": "keep",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M6-04",
            "module": "M6",
            "class": "RESIDUAL",
            "surface": "DB schema/migrations",
            "observed": f"local migrationish sql={mig_n}; Official database_baseline=production_surface",
            "required_official": "Production DB schema Capture",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M6-05",
            "module": "M6",
            "class": "RESIDUAL",
            "surface": "API product behavior depth",
            "observed": "only /meta compared",
            "required_official": "GP API behavior matrix",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M7-01",
            "module": "M7",
            "class": "RESIDUAL",
            "surface": "Capture CMS",
            "observed": "OPEN",
            "required_official": "Official CMS inventory",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M7-02",
            "module": "M7",
            "class": "RESIDUAL",
            "surface": "Capture Assets",
            "observed": "OPEN",
            "required_official": "Official asset/CDN map",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M7-03",
            "module": "M7",
            "class": "DOC_DRIFT",
            "surface": "cms-asset-matrix ambient",
            "observed": "unsplash_fallback vs catalog target",
            "required_official": "Cite live www Ambient source",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M7-04",
            "module": "M7",
            "class": "RESIDUAL",
            "surface": "cms-asset-matrix placeholders",
            "observed": "poi/hotel/transport/video placeholder",
            "required_official": "Official runtime media source",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M7-05",
            "module": "M7",
            "class": "CONFIRM_DESIGN",
            "surface": "OCS-owned rows",
            "observed": "cms_operable=false",
            "required_official": "Keep OCS vs CMS split",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M7-06",
            "module": "M7",
            "class": "ED",
            "surface": "JP Content QA CLOSED",
            "observed": "neq Official CMS Capture PASS",
            "required_official": "Do not equate",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M7-07",
            "module": "M7",
            "class": "DEFECT",
            "surface": "community media URLs",
            "observed": "uploads 404 DRC",
            "required_official": "AS-IS register",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M7-08",
            "module": "M7",
            "class": "DEFECT",
            "surface": "cms/public/announcements",
            "observed": "401 vs public 200",
            "required_official": "AS-IS register",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M8-01",
            "module": "M8",
            "class": "RESIDUAL",
            "surface": "Capture Auth/Admin/UI/i18n",
            "observed": "OPEN",
            "required_official": "Depth Capture",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M8-02",
            "module": "M8",
            "class": "CONFIRM_DESIGN",
            "surface": "FIVE-MAIN freeze",
            "observed": "structure locked",
            "required_official": "Do not thaw",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M8-03",
            "module": "M8",
            "class": "CONFIRM_DESIGN",
            "surface": "Auth UI freezes",
            "observed": "login/register frozen",
            "required_official": "Local freeze neq Capture PASS",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M8-04",
            "module": "M8",
            "class": "ED",
            "surface": "historical login 405",
            "observed": "CLOSED_REALITY",
            "required_official": "Do not reopen",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M8-05",
            "module": "M8",
            "class": "OFFICIAL_ROUTE_AS_IS",
            "surface": "route 404s",
            "observed": "market/guides hotels community/feed escrow",
            "required_official": "Capture facts",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M8-06",
            "module": "M8",
            "class": "CONFIRM_DESIGN",
            "surface": "/admin 307",
            "observed": "auth redirect",
            "required_official": "AS-IS",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M8-07",
            "module": "M8",
            "class": "DEFECT",
            "surface": "/me/payments /legal",
            "observed": "GAP 404s",
            "required_official": "AS-IS register",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M8-08",
            "module": "M8",
            "class": "RESIDUAL",
            "surface": "i18n Capture",
            "observed": "OPEN",
            "required_official": "zh/en inventory",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M9-01",
            "module": "M9",
            "class": "DOC_DRIFT",
            "surface": "whitepaper/docs Official-first",
            "observed": "NOTE_OPEN",
            "required_official": "Cite OPS-v9 or Web3 plane",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M9-02",
            "module": "M9",
            "class": "DOC_DRIFT",
            "surface": "Handbook local-first slogan",
            "observed": "git delivery",
            "required_official": "neq product SSOT",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M9-03",
            "module": "M9",
            "class": "DOC_DRIFT",
            "surface": "parallel engineering tracks",
            "observed": "Local SSOT narrative",
            "required_official": "Official-first cite",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
        {
            "id": "M9-04",
            "module": "M9",
            "class": "CONFIRM_DESIGN",
            "surface": "Dual Truth Planes",
            "observed": "ACTIVE",
            "required_official": "Keep split",
            "action": "REGISTER_ONLY",
            "optimize_official": False,
        },
    ]
    pack = {
        "schema": "traveltrust.official_first_m5_m9_depth_residuals.v1",
        "recorded_utc": "2026-08-22T03:50:00Z",
        "gate": "PRODUCT_AND_DOCUMENTATION_PARITY",
        "gate_result": "FAIL",
        "commit_identity_layer": "8ca90a08ab9ac94bd86cf4f4e55dd3705c203d66",
        "forbid_fix_until_parity_pass": True,
        "tt_production_go": "NO_GO",
        "web3_candidate_protected": "b19b85810c22677d243a82d06ebec8ebcb4d4b47",
        "action_policy": "REGISTER_ONLY_NO_OPTIMIZE_OFFICIAL",
        "m5_suspect_files": m5.get("suspects"),
        "m6_api_compare": m6.get("compare_rows"),
        "items": items,
        "counts": {
            "total": len(items),
            "by_class": dict(Counter(i["class"] for i in items)),
        },
    }
    (CAP / "M5_M9_DEPTH_RESIDUALS_20260822.json").write_text(
        json.dumps(pack, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    status = {
        "schema": "traveltrust.official_first_full_convergence_status.v1",
        "status": "IN_PROGRESS",
        "gate": "PRODUCT_AND_DOCUMENTATION_PARITY",
        "gate_result": "FAIL",
        "recorded_utc": "2026-08-22T03:50:00Z",
        "identity_layer_commit": "8ca90a08ab9ac94bd86cf4f4e55dd3705c203d66",
        "tt_production_go": "NO_GO",
        "forbid_product_optimization_until_parity_pass": True,
        "official_baseline_frozen_for_convergence": True,
        "gates": {
            "check-official-v9-local-staging-repo-1to1": "PASS",
            "check-official-v9-plane-map": "PASS",
        },
        "modules": {
            "M0_ETA": "ACTIVE",
            "M1_CAPTURE_BASELINE": "IDENTITY_FROZEN_DEPTH_OPEN",
            "M2_RESIDUALS": "OPEN",
            "M3_STAGING_WWW_ALIGN": "PASS_git_sha_pin",
            "M4_MAIN_EQ_TIP": "PASS_local",
            "M5_LOCAL_RUNTIME": "DEPTH_SCAN_REGISTERED",
            "M6_API_DB": "DEPTH_SCAN_REGISTERED",
            "M7_CMS_OCS_MEDIA": "DEPTH_SCAN_REGISTERED",
            "M8_AUTH_ADMIN_UI_I18N": "DEPTH_SCAN_REGISTERED",
            "M9_DOCS_WHITEPAPAPER": "DEPTH_SCAN_REGISTERED",
            "M10_PARITY_PASS": "NOT_ISSUED",
        },
        "depth_residuals": "evidence/GO_official_product_reality_capture/M5_M9_DEPTH_RESIDUALS_20260822.json",
        "human_ssot": "docs/runbook/TT-OFFICIAL-FIRST-FULL-CONVERGENCE-LATEST.md",
    }
    (CAP / "OFFICIAL_FIRST_FULL_CONVERGENCE_STATUS.json").write_text(
        json.dumps(status, indent=2) + "\n", encoding="utf-8"
    )
    print("OK", pack["counts"])


if __name__ == "__main__":
    main()
