/**
 * SSOT：`crates/api` 社区路由（含 **`community/posts/upload-media`**）JSON **`error`/`message`** 机读码（与 `communityApiMessageKeys.test.ts` 同源）。
 * **`COMMUNITY_API_MESSAGE_CODES`** 须保持**字典序**（见 **`communityApiMessageCodes.test.ts`**）。增删后端码时只改本文件一处，并跑 **`cd frontend && npm run test:a8-community`**（**`frontend/package.json` → `test:a8-community`**；含 **`communityApiMessageKeys`** / **`mapOrderWriteError`·`casesMatrix`/`localeHttpAndCommunity`/`fallback`** / **`communityApiMessageCodes`** 等 **A8** 切片；**`local-delivery-expanded`** / **`CI_LOCAL_RELEASE_STATE_GATES`** **不**替 **`test:a8-community`** — **TT-LOCAL §2.2**）。
 */

/** **04** §3.3 / `routes/community/common/abuse/responses.rs`：**HTTP 429** + **`Retry-After`** 的写路径反刷机读码全集（发帖/评/举报）。 */
export const COMMUNITY_ABUSE_429_CODES = [
  "post_rate_limited",
  "post_too_fast",
  "post_duplicate_body",
  "comment_rate_limited",
  "comment_too_fast",
  "comment_duplicate",
  "report_rate_limited",
  "report_too_fast",
  "report_duplicate_target",
] as const;

export const COMMUNITY_API_MESSAGE_CODES = [
  "appeal_body_required",
  "appeal_count_failed",
  "appeal_create_failed",
  "appeal_pending_exists",
  "appeal_permission_check_failed",
  "cannot_follow_self",
  "collect_create_failed",
  "comment_duplicate",
  "comment_failed",
  "comment_rate_limited",
  "comment_too_fast",
  "comments_cursor_requires_chronological_sort",
  "commerce_fields_incomplete",
  "commerce_listing_not_owned_or_unpublished",
  "community_media_object_storage_not_configured",
  "community_penalty_active",
  "community_video_requires_object_storage_multipart",
  "content_required",
  "create_post_failed",
  "db_error",
  "delete_failed",
  "empty_body",
  "feedback_create_failed",
  "feedback_media_invalid",
  "feedback_media_scheme",
  "feedback_media_too_large",
  "feedback_media_too_many",
  "file_too_large",
  "follow_create_failed",
  "forbidden",
  "friend_request_accept_failed",
  "friend_request_create_failed",
  "friend_request_not_found_or_forbidden",
  "friend_request_reject_failed",
  "invalid_base64",
  "invalid_comment_cursor",
  "invalid_commerce_market_listing_id",
  "invalid_commerce_showcase_kind",
  "invalid_conversation",
  "invalid_file_type",
  "invalid_filename",
  "invalid_id",
  "invalid_parent_comment",
  "invalid_payload",
  "invalid_post",
  "invalid_reason_code",
  "invalid_report_id",
  "invalid_request_id",
  "invalid_target_id",
  "invalid_target_type",
  "invalid_to_user_id",
  "invalid_user_id",
  "invalid_visibility_status",
  "like_create_failed",
  "list_failed",
  "media_asset_not_ready",
  "media_asset_required",
  "media_required",
  "media_url_invalid_scheme",
  "media_url_prefix_not_allowed",
  "mime_body_mismatch",
  "missing_base64_payload",
  "mkdir_failed",
  "not_found",
  "not_found_or_forbidden",
  "post_duplicate_body",
  "post_rate_limited",
  "post_too_fast",
  "report_create_failed",
  "report_duplicate_target",
  "report_fields_required",
  "report_list_failed",
  "report_load_failed",
  "report_not_appealable",
  "report_not_found",
  "report_rate_limited",
  "report_target_lookup_failed",
  "report_target_not_found",
  "report_too_fast",
  "request_id_required",
  "send_failed",
  "service_unavailable",
  "tag_required",
  "tag_too_long",
  "tags_too_many",
  "to_user_id_required",
  "unauthorized",
  "unsupported_mime",
  "update_failed",
  "video_metadata_unreadable",
  "video_too_long",
  "visibility_status_required",
  "write_failed",
] as const;

/**
 * 与 `mapOrderWriteError` 更靠前分支共用同一 `code` 时保留原映射（订单/鉴权/通用 HTTP 等）。
 * 含 **`invalid_filename`** / **`invalid_base64`**（与 **`invalid_uuid`** 同属「通用非法」分支）；**`write_failed`** 与 **`guides` 落盘** 同键走 **`common_apiHttpServer`**。
 */
const COMMUNITY_ORDER_WRITE_PRECEDENCE_CODES = new Set<string>([
  "content_required",
  "db_error",
  "forbidden",
  "invalid_base64",
  "invalid_filename",
  "invalid_id",
  "invalid_user_id",
  "not_found",
  "service_unavailable",
  "unauthorized",
  "write_failed",
]);

/** `parseResponse` → `mapOrderWriteError`：走 `community_api_msg_${code}` 的社区机读码子集。 */
export const COMMUNITY_LOCALE_FALLTHROUGH_CODES_LIST: readonly string[] =
  COMMUNITY_API_MESSAGE_CODES.filter((c) => !COMMUNITY_ORDER_WRITE_PRECEDENCE_CODES.has(c));
