import type { DemoAcquisitionListing } from "@/lib/marketSubsiteDemoTypes";
import { marketSubsiteDemoImageUrl } from "@/lib/marketSubsiteDemoImageUrl";

const img = marketSubsiteDemoImageUrl;

export const DEMO_ACQUISITION_LISTINGS: DemoAcquisitionListing[] = [
  {
    id: "a-lux-bag",
    destinationCountryIso: "CN",
    categorySlug: "luxury",
    sortKey: 50,
    title: { zh: "求带：某奢牌手袋（专柜小票）", en: "Carry request: luxury handbag (boutique receipt)" },
    summary: { zh: "美国购入 → 带回上海，需中检可验", en: "US purchase → hand-carry to Shanghai; third-party inspection OK" },
    route: { zh: "洛杉矶 → 上海", en: "Los Angeles → Shanghai" },
    bountyMinUsdc: 2200,
    bountyMaxUsdc: 2800,
    deadlineNote: { zh: "希望 45 天内到手", en: "Delivery within ~45 days preferred" },
    imageSrc: img("photo-1594223274512-ad4803739b7c"),
    inspectionStandard: {
      zh: "必须提供专柜原始小票照片与序列号清晰图；到货后支持中检或双方约定鉴定机构；与描述不符则拒收并走争议流程。",
      en: "Original boutique receipt photos + clear serial shots required; third-party authentication as agreed; disputes if not as described.",
    },
    authenticity: {
      zh: "不接受代购仓转寄；须本人或可信亲友店内购买视频片段（不露脸可）佐证。",
      en: "No drop-ship from unknown consolidators; short in-store purchase clip (face optional) as proof.",
    },
    condition: {
      zh: "全新全套：防尘袋、盒子、雪梨纸完整；五金贴膜未撕。",
      en: "Brand new full set: dust bag, box, tissue intact; hardware films untouched.",
    },
    rejections: {
      zh: "无票、剪标、陈列品、已过季两年以上款式。",
      en: "No receipt, cut tags, floor models, or styles discontinued >2 seasons ago.",
    },
    handoff: {
      zh: "上海浦东机场或静安区当面交割；可接受托管释放后再取货（按订单里程碑）。",
      en: "Handoff at PVG or Jing'an, Shanghai; escrow milestones may gate pickup timing.",
    },
    story: [
      {
        zh: "国内无货号，需指定颜色与尺寸。悬赏为 USDC 区间，实际以双边协议与托管金额为准。",
        en: "Exact color/size specified. Bounty is a USDC range; final amount follows bilateral agreement and escrow.",
      },
    ],
  },
  {
    id: "a-sneaker-drop",
    destinationCountryIso: "CN",
    categorySlug: "sneakers",
    sortKey: 40,
    title: { zh: "求带：限量球鞋 US11", en: "Carry request: limited sneakers US 11" },
    summary: { zh: "欧洲抽签款 → 北京", en: "EU raffle pair → Beijing" },
    route: { zh: "巴黎 → 北京", en: "Paris → Beijing" },
    bountyMinUsdc: 450,
    bountyMaxUsdc: 600,
    deadlineNote: { zh: "发售日起 20 天内", en: "Within ~20 days of drop" },
    imageSrc: img("photo-1542291026-7eec264c27ff"),
    inspectionStandard: {
      zh: "鞋盒八角尖、鞋标与鞋垫印刷对齐官方图；支持得物/验货宝其一。",
      en: "Box corners crisp; label and insole match official refs; one agreed verify channel.",
    },
    authenticity: { zh: "需中签邮件或门店小票截图。", en: "Raffle win email or store receipt screenshot." },
    condition: { zh: "仅试穿不接受；不接受鞋盒破损。", en: "No try-ons; no damaged shoebox." },
    rejections: { zh: "无原盒、换底、后配鞋带。", en: "No aftermarket sole swap or re-laced swaps." },
    handoff: { zh: "北京朝阳面交。", en: "Handoff in Chaoyang, Beijing." },
    story: [{ zh: "尺码固定 US11，错码拒收。", en: "US 11 only; wrong size rejected." }],
  },
  {
    id: "a-camera-lens",
    destinationCountryIso: "CN",
    categorySlug: "electronics",
    sortKey: 30,
    title: { zh: "求带：长焦镜头（行货包装）", en: "Carry request: telephoto lens (sealed domestic SKU)" },
    summary: { zh: "日本免税 → 广州", en: "Japan duty-free → Guangzhou" },
    route: { zh: "东京 → 广州", en: "Tokyo → Guangzhou" },
    bountyMinUsdc: 120,
    bountyMaxUsdc: 180,
    deadlineNote: { zh: "30 天内", en: "Within ~30 days" },
    imageSrc: img("photo-1502920917128-1aa500764cbd"),
    inspectionStandard: {
      zh: "封条完整可拍照；拆封须当面并录像，序列号与保修卡一致。",
      en: "Seals intact or unboxed on camera; serial matches warranty card.",
    },
    authenticity: { zh: "需 BicCamera/Yodobashi 小票。", en: "Receipt from named retailers." },
    condition: { zh: "不接受样机或已注册保修。", en: "No demo units or pre-registered warranty." },
    rejections: { zh: "水货无票。", en: "Grey import without receipt." },
    handoff: { zh: "广州白云机场 T2。", en: "CAN Terminal 2." },
    story: [{ zh: "易碎品需妥善缓冲包装。", en: "Fragile; padded packing required." }],
  },
  {
    id: "a-vitamins-bundle",
    destinationCountryIso: "CN",
    categorySlug: "health",
    sortKey: 20,
    title: { zh: "求带：复合维生素套装", en: "Carry request: vitamin bundle" },
    summary: { zh: "美国 OTC → 深圳", en: "US OTC → Shenzhen" },
    route: { zh: "旧金山 → 深圳", en: "San Francisco → Shenzhen" },
    bountyMinUsdc: 80,
    bountyMaxUsdc: 120,
    deadlineNote: { zh: "宽松 60 天", en: "Flexible ~60 days" },
    imageSrc: img("photo-1587854692152-cbe660dbde88"),
    inspectionStandard: {
      zh: "保质期不低于 12 个月；瓶口密封完好；批次号拍照。",
      en: "≥12 months shelf life; sealed caps; batch photos.",
    },
    authenticity: { zh: "需 CVS/Target 小票。", en: "CVS/Target receipt." },
    condition: { zh: "不接受临期或胀罐。", en: "No near-expiry or bloated seals." },
    rejections: { zh: "拆盒混装。", en: "No mixed loose pills." },
    handoff: { zh: "深圳湾口岸附近面交。", en: "Near Shenzhen Bay Port." },
    story: [{ zh: "个人用量范围内；禁运品类请勿接单。", en: "Personal-use quantities; no prohibited goods." }],
  },
  {
    id: "a-watch-straps",
    destinationCountryIso: "CN",
    categorySlug: "accessories",
    sortKey: 10,
    title: { zh: "求带：原厂表带两条", en: "Carry request: two OEM watch straps" },
    summary: { zh: "瑞士专柜 → 成都", en: "Swiss boutique → Chengdu" },
    route: { zh: "苏黎世 → 成都", en: "Zurich → Chengdu" },
    bountyMinUsdc: 200,
    bountyMaxUsdc: 260,
    deadlineNote: { zh: "21 天内", en: "Within ~21 days" },
    imageSrc: img("photo-1524592094714-0f0654e20314"),
    inspectionStandard: {
      zh: "需专柜袋与贴纸完整；长度规格 20/18 各一。",
      en: "Boutique bag and stickers intact; sizes 20mm and 18mm one each.",
    },
    authenticity: { zh: "保卡照片与店铺章。", en: "Warranty card photo with store stamp." },
    condition: { zh: "不接受陈列折痕过深。", en: "No deep creases from long display." },
    rejections: { zh: "第三方表匠改装件。", en: "No third-party modified parts." },
    handoff: { zh: "成都双流面交。", en: "Handoff near Chengdu Shuangliu." },
    story: [{ zh: "小件高价，建议托管分阶段释放。", en: "High value small item; staged escrow release recommended." }],
  },
];
