/**
 * Hero / 首屏布局 token — 375/390 窄屏 + 桌面分栏（TT-PH1-150～163 · ①）
 * V2 真源：`@/lib/marketingUi` · V1：`frontend/archive/ui-v1/`
 */
export {
  TT_MARKETING_HERO_CONTENT_SHELL_CLASS as TT_HERO_CONTENT_SHELL_CLASS,
  TT_MARKETING_HERO_GLOBE_VIEWPORT_CLASS as TT_HERO_GLOBE_VIEWPORT_CLASS,
  TT_MARKETING_HERO_COPY_COL_CLASS as TT_HERO_COPY_COL_CLASS,
  TT_MARKETING_HERO_UNIFIED_SCRIM_CLASS as TT_HERO_UNIFIED_SCRIM_CLASS,
  TT_MARKETING_HERO_COPY_PANEL_SCRIM_CLASS as TT_HERO_COPY_PANEL_SCRIM_CLASS,
  TT_MARKETING_COPY_CARD_CLASS as TT_HERO_COPY_CARD_CLASS,
  TT_MARKETING_HERO_CHIP_ITEM_CLASS as TT_HERO_CHIP_ITEM_CLASS,
  TT_MARKETING_DISCLAIMER_CLASS as TT_HERO_DISCLAIMER_CLASS,
} from "@/lib/marketingUi";

export { TT_MARKETING_LANDING_CHROME_CLASS as TT_LANDING_CHROME_CLASS } from "@/lib/marketingUi";

export {
  TT_TRAVELTRUST_PAGE_BLEED_BAND_CLASS,
  TT_TRAVELTRUST_PAGE_FRAME_CLASS,
  TT_TRAVELTRUST_HERO_CONTENT_OFFSET_CLASS,
} from "@/lib/traveltrustPageLayout";
