//! **F-031 / F-032 / F-033** · **`router::app`** + **`DATABASE_URL`** · **`Router::oneshot`** **API·IT 正路径**（与 **`main`** 中间件序一致；**非**子域 **`community::router()`**/**`trust_growth::router()`**/**`itineraries::router()`** 单栈）。**F-032·Admin obs**：**`GET /api/v1/admin/trust-growth/observability`** 须 **`sessions` Bearer** + **`ChainOffStore.users`** 种子（**`app_with_pool_seeded_users`**）。**F-032·Admin control**：**`PATCH /api/v1/admin/trust-growth/control`**（**`matrix_93_b_tgr_002c_f032_patch_admin_trust_growth_control_weights_frozen_app_stack_ok_pg`**；**v1.4.258**）。**F-032·config**：**`GET /api/v1/trust-growth/config`** **`autopilot_generation`** **↔** **`trust_growth_runtime_state`** **PG**（**`matrix_93_b_tgr_001_f032_get_trust_growth_config_autopilot_gen_matches_runtime_state_pg`**）。**v1.4.260**：**`001b`** **`ingest` 后** **`trust_growth_autopilot_gen_for_env`** **对拍** **`GET …/config`**（**`weights_frozen=false` 可推进代**）；**`cleanup_*`** **`DELETE FROM sessions`** **先行**。**v1.4.256**：**`matrix_93_d_com_011b_f031_*`**（**`Authorization: Bearer`** + **`sessions`**）；**`matrix_93_b_tgr_001b_f032_post_ingest_then_get_trust_growth_config_ok_pg`**（**ingest→config** **链式**）；**`matrix_93_d_itn_002b_f033_*`** / **`matrix_93_d_itn_003b_f033_*`**（**Bearer** **替代** **`x-user-id`**）。**v1.4.273**：**`matrix_93_d_com_011c_f031_bearer_post_then_anon_feed_includes_post_app_stack_ok_pg`**（**Bearer `POST …/posts`**→**无头 `GET …/feed`** **`posts[].id`**）。**v1.4.274**：**`matrix_93_d_com_011d_f031_bearer_post_select_commerce_then_hot_feed_includes_post_app_stack_ok_pg`**（**`SELECT commerce_*` PG 锚** **+** **无头 `GET …/feed?mode=hot`**）。**v1.4.275**：**`matrix_93_d_com_011e_f031_bearer_post_then_bearer_follow_feed_ok_shape_app_stack_ok_pg`**（**Bearer `POST …/posts`**→**Bearer `GET …/feed?mode=follow`** **`200`** **`posts`** **数组**）。**v1.4.276**：**`matrix_93_d_com_011f_f031_follower_get_follow_feed_includes_author_acquisition_post_app_stack_ok_pg`**（**`insert_follow`** **+** **作者 `acquisition_led` 发帖**→**关注者 `mode=follow`** **`posts[].id`**）。
//!
//! **93**：**`matrix_93_d_com_011_f031_*`** / **`matrix_93_d_com_011b_f031_*`** / **`matrix_93_d_com_011c_f031_*`** / **`matrix_93_d_com_011d_f031_*`** / **`matrix_93_d_com_011e_f031_*`** / **`matrix_93_d_com_011f_f031_*`** ↔ **D-COM-011**/**F-031**（**`POST …/community/posts`** **+** **`GET …/community/feed`** **`posts[].id`**；**`011c_*`** = **Bearer** **发帖** **后** **匿名 Feed 读回**；**`011d_*`** = **`commerce_*` PG** **+** **`mode=hot`** **匿名 Feed**；**`011e_*`** = **Bearer `mode=follow`** **Feed 形状**；**`011f_*`** = **`community_follows`** **+** **关注者读** **`mode=follow`** **含 commerce 帖**）；**`matrix_93_b_tgr_001_f032_*`** / **`matrix_93_b_tgr_001b_f032_*`** / **`matrix_93_b_tgr_002c_f032_*`** ↔ **B-TGR-001**/**F-032**；**`matrix_93_d_itn_002_*`** / **`matrix_93_d_itn_002b_*`** / **`matrix_93_d_itn_003_*`** / **`matrix_93_d_itn_003b_*`** ↔ **D-ITN-002**/**D-ITN-003**/**F-033**（**`POST|GET …/itineraries/custom*`**；**`spec/93-全站功能验证矩阵-域别回归清单.md`**）。
//!
//! **跳过条件**：未设置 **`DATABASE_URL`**。三测串行以避免 PG 争用。

mod f031_abc;
mod f031_def;
mod f032;
mod f033;
mod helpers;
