import type { CommunityCommentSort, CommunityReportReasonCode } from "@/lib/apiClient/community";
import type { CommunityPost, CommunityComment } from "@/lib/communityMockData";
import type { CommunityFeedCardAuthorFollow } from "@/components/community/CommunityFeedCard";
import type { CommunityReportFlowContext } from "@/components/community/useCommunityPostReport";
import type { PublishDrawerProps } from "@/components/community/PublishDrawer/types";
export interface CommunityFeedMainPortalsProps {
  t: (key: string) => string;
  toast: string | null;
  toastBodyOverride: string | null;
  toastHint: string | null;
  reportSuccessId: string | null;
  commentPost: CommunityPost | null;
  commentsForPost: CommunityComment[];
  apiCommentsByPostId?: Record<string, CommunityComment[]>;
  closeCommentDrawer: () => void;
  handleCommentSend: (postId: string, content: string, parentId?: string) => void | Promise<void>;
  isLoggedIn: boolean;
  authLoading: boolean;
  meUserId: string | null;
  handleReportComment: (post: CommunityPost, c: CommunityComment) => void;
  commentSendFailed: boolean;
  commentSendErrorMessage: string | null;
  commentFieldMessages: Record<string, string> | null;
  clearCommentSendError: () => void;
  commentsLoadError: string | null;
  retryCommentsLoad: () => void;
  commentSort: CommunityCommentSort;
  setCommentSort: (s: CommunityCommentSort) => void;
  commentsHasMore: boolean;
  loadMoreComments: () => void;
  commentsLoadMoreBusy: boolean;
  reportContext: CommunityReportFlowContext | null;
  closeReportDrawer: () => void;
  handleReportSubmit: (reason: CommunityReportReasonCode, details: string) => void | Promise<void>;
  reportSendFailed: boolean;
  reportErrorMessage: string | null;
  reportFieldMessages: Record<string, string> | null;
  clearReportSendError: () => void;
  detailPost: CommunityPost | null;
  commentsForDetail: CommunityComment[];
  closeDetailDrawer: () => void;
  /** Feed 卡片评论入口：打开详情并滚至评论区 */
  detailFocusComments?: boolean;
  handleReport: (post: CommunityPost) => void;
  likedPostIds: ReadonlySet<string>;
  collectedPostIds: ReadonlySet<string>;
  handleLike: (postId: string, hint?: { serverLiked?: boolean }) => void | Promise<void>;
  handleCollect: (postId: string, hint?: { serverCollected?: boolean }) => void | Promise<void>;
  detailPostAuthorFollow: CommunityFeedCardAuthorFollow | undefined;
  hrefTopicPathForTag: (tag: string) => string;
  publishOpen: boolean;
  closePublishDrawer: () => void;
  handlePublishSubmit: PublishDrawerProps["onSubmit"];
  publishSendFailed: boolean;
  publishErrorMessage: string | null;
  publishFieldMessages: Record<string, string> | null;
  clearPublishSendError: () => void;
  detailVideoFeedPostIds?: readonly string[];
  onDetailVideoFeedSelect?: (postId: string) => void;
  onDetailVideoFeedLoadMore?: () => void;
  detailVideoFeedLoadingMore?: boolean;
}
