import type { Dispatch, MutableRefObject, SetStateAction } from "react";
import type { ReadonlyURLSearchParams } from "next/navigation";
import type { CommunityPost, CommunityComment } from "@/lib/communityMockData";
import type { CommunityMeUser } from "@/components/community/CommunityAuthContext";
import type { OpenPublishFn } from "@/components/community/CommunityPublishContext";
import type { SortBy } from "@/components/community/communityFeedConstants";
import type { UseCommunityFeedFiltersReturn } from "@/components/community/useCommunityFeedFilters";
import type { CommunityFeedPostDeepLinkAlert } from "@/components/community/useCommunityFeedPostDeepLink";
import type { LocaleInterpolationVars } from "@/lib/i18n";

export type CommunityFeedHookTFunc = (key: string, vars?: LocaleInterpolationVars) => string;

export type CommunityFeedHookRouter = { replace: (href: string, navOptions?: { scroll?: boolean }) => void };

/** `useCommunityFeedTopicReportCommentChain` 入参（与 bootstrap assemble 同源）。 */
export type UseCommunityFeedTopicReportCommentChainOptions = {
  t: CommunityFeedHookTFunc;
  dash: string;
  searchParams: ReadonlyURLSearchParams;
  pathname: string | null;
  router: CommunityFeedHookRouter;
  sortBy: SortBy;
  setTagFilterState: Dispatch<SetStateAction<string | null>>;
  setDestinationFilterFromUrl: (value: string) => void;
  searchQuery: string;
  setSearchQuery: (q: string) => void;
  clearFiltersFromHook: () => void;
  setToastHint: Dispatch<SetStateAction<string | null>>;
  setToastBodyOverride: Dispatch<SetStateAction<string | null>>;
  setToast: Dispatch<SetStateAction<string | null>>;
  scheduleToastClear: (ms: number) => void;
  allPosts: CommunityPost[];
  searchFilteredPosts: CommunityPost[];
  postDeepLinkLastId: string | null;
  setDetailPost: Dispatch<SetStateAction<CommunityPost | null>>;
  setPostDeepLinkBusy: Dispatch<SetStateAction<boolean>>;
  setPostDeepLinkAlert: Dispatch<SetStateAction<CommunityFeedPostDeepLinkAlert | null>>;
  setPostDeepLinkLastId: Dispatch<SetStateAction<string | null>>;
  isLoggedIn: boolean;
  setShowLoginModal: Dispatch<SetStateAction<boolean>>;
  setFocusReturn: (target: HTMLElement | null) => void;
  setDetailFocusComments: Dispatch<SetStateAction<boolean>>;
  setCommentPost: Dispatch<SetStateAction<CommunityPost | null>>;
  setReportSuccessId: Dispatch<SetStateAction<string | null>>;
  feedPage: number;
  setFeedPage: Dispatch<SetStateAction<number>>;
  filterApi: UseCommunityFeedFiltersReturn;
  feedTagFromUrl: string | null;
  feedNextCursor: string | null;
  authLoading: boolean;
  registerOpenPublish?: (fn: OpenPublishFn) => () => void;
  setPublishOpen: Dispatch<SetStateAction<boolean>>;
  setPublishSendFailed: Dispatch<SetStateAction<boolean>>;
  setPublishErrorMessage: Dispatch<SetStateAction<string | null>>;
  setPublishFieldMessages: Dispatch<SetStateAction<Record<string, string> | null>>;
  showLoginModal: boolean;
  commentPost: CommunityPost | null;
  detailPost: CommunityPost | null;
  localCommentsByPostId: Record<string, CommunityComment[]>;
  apiCommentsByPostId: Record<string, CommunityComment[]>;
  setCommentsRetryTick: Dispatch<SetStateAction<number>>;
  setCommentSendFailed: Dispatch<SetStateAction<boolean>>;
  setCommentSendErrorMessage: Dispatch<SetStateAction<string | null>>;
  setCommentFieldMessages: Dispatch<SetStateAction<Record<string, string> | null>>;
  communityUser: CommunityMeUser | null;
  feedApiRefetch: () => void;
  setLocalCommentsByPostId: Dispatch<SetStateAction<Record<string, CommunityComment[]>>>;
  setApiPosts: Dispatch<SetStateAction<CommunityPost[]>>;
  setLocalPosts: Dispatch<SetStateAction<CommunityPost[]>>;
};

/** `useCommunityFeedTailInteractions` 入参（与 bootstrap assemble 同源）。 */
export type UseCommunityFeedTailInteractionsOptions = {
  detailPost: CommunityPost | null;
  communityUserId: string | null | undefined;
  followingAuthorIdSet: Set<string>;
  followBusyAuthorId: string | null;
  handleAuthorFollowToggle: (authorId: string) => void | Promise<void>;
  hasMore: boolean;
  feedNextCursor: string | null;
  feedApiRefetch: () => void;
  feedApiLoadMore: (cursor: string) => Promise<unknown>;
  setFeedError: Dispatch<SetStateAction<string | null>>;
  setFeedPage: Dispatch<SetStateAction<number>>;
  setFeedLoadingMore: Dispatch<SetStateAction<boolean>>;
  setToastHint: Dispatch<SetStateAction<string | null>>;
  setToastBodyOverride: Dispatch<SetStateAction<string | null>>;
  setToast: Dispatch<SetStateAction<string | null>>;
  scheduleToastClear: (ms: number) => void;
  t: CommunityFeedHookTFunc;
  pullY: number;
  setPullY: Dispatch<SetStateAction<number>>;
  feedLoading: boolean;
  authLoading: boolean;
  isLoggedIn: boolean;
  focusReturnTargetRef: MutableRefObject<HTMLElement | null>;
  setFocusReturn: (el: HTMLElement | null) => void;
  setShowLoginModal: Dispatch<SetStateAction<boolean>>;
  setPublishOpen: Dispatch<SetStateAction<boolean>>;
  setPublishSendFailed: Dispatch<SetStateAction<boolean>>;
  setPublishErrorMessage: Dispatch<SetStateAction<string | null>>;
  setCommentPost: Dispatch<SetStateAction<CommunityPost | null>>;
  setDetailPost: Dispatch<SetStateAction<CommunityPost | null>>;
};
