import type { Dispatch, RefObject, SetStateAction, TouchEvent, KeyboardEvent as ReactKeyboardEvent, PointerEvent as ReactPointerEvent } from "react";
import type { CommunityVideoOverlayProps } from "./communityVideoOverlayTypes";

export type CommunityVideoOverlayController = {
  videoTitleId: string;
  videoDescId: string;
  videoRef: RefObject<HTMLVideoElement | null>;
  bindOverlayStageRef: (el: HTMLDivElement | null) => void;
  wheelAreaRef: RefObject<HTMLDivElement | null>;
  progressTrackRef: RefObject<HTMLDivElement | null>;
  safeIndex: number;
  current: CommunityVideoOverlayProps["items"][number] | undefined;
  src: string;
  poster: string | undefined;
  paused: boolean;
  muted: boolean;
  videoError: boolean;
  progress: number;
  clockCur: number;
  clockDur: number;
  slideDir: 1 | -1 | 0;
  buffering: boolean;
  setBuffering: Dispatch<SetStateAction<boolean>>;
  chromeVisible: boolean;
  showChrome: () => void;
  wheelAreaElRef: RefObject<HTMLDivElement | null>;
  bindWheelAreaRef: (el: HTMLDivElement | null) => void;
  inFullscreen: boolean;
  atFirst: boolean;
  atLast: boolean;
  showNoVideo: boolean;
  fsSupported: boolean;
  onTouchStart: (e: TouchEvent) => void;
  onTouchEnd: (e: TouchEvent) => void;
  goNext: () => void;
  goPrev: () => void;
  togglePlay: () => void;
  toggleStageFullscreen: () => void;
  setMuted: Dispatch<SetStateAction<boolean>>;
  setPaused: Dispatch<SetStateAction<boolean>>;
  setVideoError: Dispatch<SetStateAction<boolean>>;
  onTimeUpdate: () => void;
  onLoadedMetadata: () => void;
  onProgressPointerDown: (e: ReactPointerEvent) => void;
  onProgressKeyDown: (e: ReactKeyboardEvent) => void;
  onClose: () => void;
};
